/* Generated by Yosys 0.45 (git sha1 9ed031ddd, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "counter.v:1.1-95.10" *)
module counter(clk, rst, mode, cnt);
  (* src = "counter.v:32.5-38.8" *)
  wire [9:0] _000_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _001_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _002_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _003_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _004_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _005_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _006_;
  (* src = "counter.v:36.20-36.33|map.v:9.26-9.27" *)
  wire [9:0] _007_;
  (* src = "counter.v:36.20-36.33|map.v:10.26-10.27" *)
  wire [9:0] _008_;
  (* src = "counter.v:36.20-36.33|map.v:15.22-15.23" *)
  wire [10:0] _009_;
  (* src = "counter.v:36.20-36.33|map.v:13.22-13.23" *)
  wire [10:0] _010_;
  (* src = "counter.v:36.20-36.33|map.v:14.22-14.23" *)
  wire [10:0] _011_;
  (* src = "counter.v:36.20-36.33|map.v:11.26-11.27" *)
  wire [10:0] _012_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [-1:0] _013_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [9:0] _014_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [9:0] _015_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [9:1] _016_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [9:2] _017_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [9:3] _018_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [9:4] _019_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [9:5] _020_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [9:6] _021_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [9:7] _022_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [9:8] _023_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _024_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire _025_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _026_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [1:0] _027_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [1:0] _028_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _029_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [2:0] _030_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [2:0] _031_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [2:1] _032_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _033_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [3:0] _034_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [3:0] _035_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [3:1] _036_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [3:2] _037_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _038_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [4:0] _039_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [4:0] _040_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [4:1] _041_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [4:2] _042_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [4:3] _043_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _044_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [5:0] _045_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [5:0] _046_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [5:1] _047_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [5:2] _048_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [5:3] _049_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [5:4] _050_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _051_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [6:0] _052_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [6:0] _053_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [6:1] _054_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [6:2] _055_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [6:3] _056_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [6:4] _057_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [6:5] _058_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _059_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [7:0] _060_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [7:0] _061_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [7:1] _062_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [7:2] _063_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [7:3] _064_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [7:4] _065_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [7:5] _066_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [7:6] _067_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _068_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [8:0] _069_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [8:0] _070_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [8:1] _071_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [8:2] _072_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [8:3] _073_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [8:4] _074_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [8:5] _075_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [8:6] _076_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [8:7] _077_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _078_;
  (* src = "counter.v:36.20-36.33" *)
  wire [9:0] _079_;
  (* src = "counter.v:23.21-23.37" *)
  wire _080_;
  (* src = "counter.v:26.26-26.42" *)
  wire _081_;
  (* src = "counter.v:14.21-14.36" *)
  wire _082_;
  (* src = "counter.v:17.26-17.41" *)
  wire _083_;
  (* src = "counter.v:13.17-13.32" *)
  wire _084_;
  (* src = "counter.v:22.17-22.31" *)
  wire _085_;
  wire [9:0] _086_;
  wire [9:0] _087_;
  wire [9:0] _088_;
  wire [9:0] _089_;
  wire [9:0] _090_;
  wire [9:0] _091_;
  wire [9:0] _092_;
  wire [9:0] _093_;
  wire [9:0] _094_;
  wire [9:0] _095_;
  (* src = "counter.v:36.20-36.33|map.v:39.16-39.21" *)
  wire [10:0] _096_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _097_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _098_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _099_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _100_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _101_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _102_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _103_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _104_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _105_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _106_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _107_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _108_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _109_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _110_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _111_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _112_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _113_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _114_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _115_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _116_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _117_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _118_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _119_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _120_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _121_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _122_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _123_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _124_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _125_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _126_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _127_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _128_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _129_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _130_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _131_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _132_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _133_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _134_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _135_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _136_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _137_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _138_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _139_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _140_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _141_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _142_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _143_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _144_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _145_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _146_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _147_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _148_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _149_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _150_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _151_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _152_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _153_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _154_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _155_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _156_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _157_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _158_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _159_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _160_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _161_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _162_;
  (* src = "counter.v:36.20-36.33|map.v:40.16-40.21" *)
  wire [10:0] _163_;
  (* src = "counter.v:36.20-36.33|map.v:44.29-44.60" *)
  wire [8:0] _164_;
  (* src = "counter.v:3.17-3.20" *)
  input clk;
  wire clk;
  (* src = "counter.v:6.29-6.32" *)
  output [9:0] cnt;
  reg [9:0] cnt = 10'h3ce;
  (* src = "counter.v:5.17-5.21" *)
  input mode;
  wire mode;
  (* src = "counter.v:4.17-4.20" *)
  input rst;
  wire rst;
  (* src = "counter.v:8.22-8.29" *)
  wire [9:0] summand;
  assign _080_ = $signed(cnt) >= (* src = "counter.v:23.21-23.37" *) $signed(10'h323);
  assign _081_ = $signed(cnt) >= (* src = "counter.v:26.26-26.42" *) $signed(10'h32c);
  assign _082_ = $signed(cnt) <= (* src = "counter.v:14.21-14.36" *) $signed(10'h0e6);
  assign _083_ = $signed(cnt) <= (* src = "counter.v:17.26-17.41" *) $signed(10'h0e1);
  assign _084_ = $signed(cnt) != (* src = "counter.v:13.17-13.32" *) $signed(10'h3f0);
  assign _085_ = $signed(cnt) != (* src = "counter.v:22.17-22.31" *) $signed(10'h3fe);
  (* src = "counter.v:32.5-38.8" *)
  always @(posedge clk)
    cnt <= _000_;
  assign _000_ = rst ? (* full_case = 32'd1 *) (* src = "counter.v:33.13-33.16|counter.v:33.9-37.12" *) 10'h3ce : _079_;
  assign _086_ = _081_ ? (* full_case = 32'd1 *) (* src = "counter.v:26.26-26.42|counter.v:26.22-28.16" *) 10'h3ee : 10'h000;
  assign _087_ = _085_ ? (* full_case = 32'd1 *) (* src = "counter.v:22.17-22.31|counter.v:22.13-28.16" *) 10'hxxx : _086_;
  assign _006_ = mode ? (* full_case = 32'd1 *) (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *) 10'hxxx : _087_;
  assign _088_ = _080_ ? (* full_case = 32'd1 *) (* src = "counter.v:23.21-23.37|counter.v:23.17-25.20" *) 10'h3f7 : 10'h000;
  assign _089_ = _085_ ? (* full_case = 32'd1 *) (* src = "counter.v:22.17-22.31|counter.v:22.13-28.16" *) _088_ : 10'hxxx;
  assign _005_ = mode ? (* full_case = 32'd1 *) (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *) 10'hxxx : _089_;
  assign _090_ = _085_ ? (* full_case = 32'd1 *) (* src = "counter.v:22.17-22.31|counter.v:22.13-28.16" *) _005_ : _006_;
  assign _004_ = mode ? (* full_case = 32'd1 *) (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *) 10'hxxx : _090_;
  assign _091_ = _083_ ? (* full_case = 32'd1 *) (* src = "counter.v:17.26-17.41|counter.v:17.22-19.16" *) 10'h00a : 10'h000;
  assign _092_ = _084_ ? (* full_case = 32'd1 *) (* src = "counter.v:13.17-13.32|counter.v:13.13-19.16" *) 10'hxxx : _091_;
  assign _003_ = mode ? (* full_case = 32'd1 *) (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *) _092_ : 10'hxxx;
  assign _093_ = _082_ ? (* full_case = 32'd1 *) (* src = "counter.v:14.21-14.36|counter.v:14.17-16.20" *) 10'h005 : 10'h000;
  assign _094_ = _084_ ? (* full_case = 32'd1 *) (* src = "counter.v:13.17-13.32|counter.v:13.13-19.16" *) _093_ : 10'hxxx;
  assign _002_ = mode ? (* full_case = 32'd1 *) (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *) _094_ : 10'hxxx;
  assign _095_ = _084_ ? (* full_case = 32'd1 *) (* src = "counter.v:13.17-13.32|counter.v:13.13-19.16" *) _002_ : _003_;
  assign _001_ = mode ? (* full_case = 32'd1 *) (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *) _095_ : 10'hxxx;
  assign summand = mode ? (* full_case = 32'd1 *) (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *) _001_ : _004_;
  assign _096_ = cnt & (* src = "counter.v:36.20-36.33|map.v:39.16-39.21" *) summand;
  assign _097_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _026_;
  assign _098_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _028_;
  assign _099_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _029_;
  assign _100_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _031_;
  assign _101_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _032_;
  assign _102_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _033_;
  assign _103_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _035_;
  assign _104_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _036_;
  assign _105_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _037_;
  assign _106_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _038_;
  assign _107_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _040_;
  assign _108_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _041_;
  assign _109_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _042_;
  assign _110_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _043_;
  assign _111_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _044_;
  assign _112_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _046_;
  assign _113_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _047_;
  assign _114_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _048_;
  assign _115_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _049_;
  assign _116_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _050_;
  assign _117_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _051_;
  assign _118_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _053_;
  assign _119_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _054_;
  assign _120_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _055_;
  assign _121_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _056_;
  assign _122_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _057_;
  assign _123_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _058_;
  assign _124_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _059_;
  assign _125_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _061_;
  assign _126_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _062_;
  assign _127_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _063_;
  assign _128_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _064_;
  assign _129_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _065_;
  assign _130_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _066_;
  assign _131_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _067_;
  assign _132_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _068_;
  assign _133_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _070_;
  assign _134_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _071_;
  assign _135_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _072_;
  assign _136_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _073_;
  assign _137_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _074_;
  assign _138_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _075_;
  assign _139_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _076_;
  assign _140_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _077_;
  assign _141_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _078_;
  assign _142_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _015_;
  assign _143_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _016_;
  assign _144_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _017_;
  assign _145_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _018_;
  assign _146_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _019_;
  assign _147_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _020_;
  assign _148_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _021_;
  assign _149_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _022_;
  assign _150_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _023_;
  assign _151_ = & (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *) _024_;
  assign _152_ = | (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *) _013_;
  assign _153_ = | (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *) _025_;
  assign _154_ = | (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *) _027_;
  assign _155_ = | (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *) _030_;
  assign _156_ = | (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *) _034_;
  assign _157_ = | (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *) _039_;
  assign _158_ = | (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *) _045_;
  assign _159_ = | (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *) _052_;
  assign _160_ = | (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *) _060_;
  assign _161_ = | (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *) _069_;
  assign _162_ = | (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *) _014_;
  assign _163_ = cnt ^ (* src = "counter.v:36.20-36.33|map.v:40.16-40.21" *) summand;
  assign _164_ = _011_[9:1] ^ (* src = "counter.v:36.20-36.33|map.v:44.29-44.60" *) _009_[9:1];
  assign _010_ = _096_;
  assign _011_ = _163_;
  assign _079_[0] = _011_[0];
  assign _012_[10] = _009_[10];
  assign _079_[9:1] = _164_;
  assign _009_[0] = _152_;
  assign _009_[1] = _153_;
  assign _025_ = _097_;
  assign _026_ = _010_[0];
  assign _009_[2] = _154_;
  assign _027_[0] = _098_;
  assign _028_[0] = _010_[0];
  assign _028_[1] = _011_[1];
  assign _027_[1] = _099_;
  assign _029_ = _010_[1];
  assign _009_[3] = _155_;
  assign _030_[0] = _100_;
  assign _031_[0] = _010_[0];
  assign _031_[1] = _011_[1];
  assign _031_[2] = _011_[2];
  assign _030_[1] = _101_;
  assign _032_[1] = _010_[1];
  assign _032_[2] = _011_[2];
  assign _030_[2] = _102_;
  assign _033_ = _010_[2];
  assign _009_[4] = _156_;
  assign _034_[0] = _103_;
  assign _035_[0] = _010_[0];
  assign _035_[1] = _011_[1];
  assign _035_[2] = _011_[2];
  assign _035_[3] = _011_[3];
  assign _034_[1] = _104_;
  assign _036_[1] = _010_[1];
  assign _036_[2] = _011_[2];
  assign _036_[3] = _011_[3];
  assign _034_[2] = _105_;
  assign _037_[2] = _010_[2];
  assign _037_[3] = _011_[3];
  assign _034_[3] = _106_;
  assign _038_ = _010_[3];
  assign _009_[5] = _157_;
  assign _039_[0] = _107_;
  assign _040_[0] = _010_[0];
  assign _040_[1] = _011_[1];
  assign _040_[2] = _011_[2];
  assign _040_[3] = _011_[3];
  assign _040_[4] = _011_[4];
  assign _039_[1] = _108_;
  assign _041_[1] = _010_[1];
  assign _041_[2] = _011_[2];
  assign _041_[3] = _011_[3];
  assign _041_[4] = _011_[4];
  assign _039_[2] = _109_;
  assign _042_[2] = _010_[2];
  assign _042_[3] = _011_[3];
  assign _042_[4] = _011_[4];
  assign _039_[3] = _110_;
  assign _043_[3] = _010_[3];
  assign _043_[4] = _011_[4];
  assign _039_[4] = _111_;
  assign _044_ = _010_[4];
  assign _009_[6] = _158_;
  assign _045_[0] = _112_;
  assign _046_[0] = _010_[0];
  assign _046_[1] = _011_[1];
  assign _046_[2] = _011_[2];
  assign _046_[3] = _011_[3];
  assign _046_[4] = _011_[4];
  assign _046_[5] = _011_[5];
  assign _045_[1] = _113_;
  assign _047_[1] = _010_[1];
  assign _047_[2] = _011_[2];
  assign _047_[3] = _011_[3];
  assign _047_[4] = _011_[4];
  assign _047_[5] = _011_[5];
  assign _045_[2] = _114_;
  assign _048_[2] = _010_[2];
  assign _048_[3] = _011_[3];
  assign _048_[4] = _011_[4];
  assign _048_[5] = _011_[5];
  assign _045_[3] = _115_;
  assign _049_[3] = _010_[3];
  assign _049_[4] = _011_[4];
  assign _049_[5] = _011_[5];
  assign _045_[4] = _116_;
  assign _050_[4] = _010_[4];
  assign _050_[5] = _011_[5];
  assign _045_[5] = _117_;
  assign _051_ = _010_[5];
  assign _009_[7] = _159_;
  assign _052_[0] = _118_;
  assign _053_[0] = _010_[0];
  assign _053_[1] = _011_[1];
  assign _053_[2] = _011_[2];
  assign _053_[3] = _011_[3];
  assign _053_[4] = _011_[4];
  assign _053_[5] = _011_[5];
  assign _053_[6] = _011_[6];
  assign _052_[1] = _119_;
  assign _054_[1] = _010_[1];
  assign _054_[2] = _011_[2];
  assign _054_[3] = _011_[3];
  assign _054_[4] = _011_[4];
  assign _054_[5] = _011_[5];
  assign _054_[6] = _011_[6];
  assign _052_[2] = _120_;
  assign _055_[2] = _010_[2];
  assign _055_[3] = _011_[3];
  assign _055_[4] = _011_[4];
  assign _055_[5] = _011_[5];
  assign _055_[6] = _011_[6];
  assign _052_[3] = _121_;
  assign _056_[3] = _010_[3];
  assign _056_[4] = _011_[4];
  assign _056_[5] = _011_[5];
  assign _056_[6] = _011_[6];
  assign _052_[4] = _122_;
  assign _057_[4] = _010_[4];
  assign _057_[5] = _011_[5];
  assign _057_[6] = _011_[6];
  assign _052_[5] = _123_;
  assign _058_[5] = _010_[5];
  assign _058_[6] = _011_[6];
  assign _052_[6] = _124_;
  assign _059_ = _010_[6];
  assign _009_[8] = _160_;
  assign _060_[0] = _125_;
  assign _061_[0] = _010_[0];
  assign _061_[1] = _011_[1];
  assign _061_[2] = _011_[2];
  assign _061_[3] = _011_[3];
  assign _061_[4] = _011_[4];
  assign _061_[5] = _011_[5];
  assign _061_[6] = _011_[6];
  assign _061_[7] = _011_[7];
  assign _060_[1] = _126_;
  assign _062_[1] = _010_[1];
  assign _062_[2] = _011_[2];
  assign _062_[3] = _011_[3];
  assign _062_[4] = _011_[4];
  assign _062_[5] = _011_[5];
  assign _062_[6] = _011_[6];
  assign _062_[7] = _011_[7];
  assign _060_[2] = _127_;
  assign _063_[2] = _010_[2];
  assign _063_[3] = _011_[3];
  assign _063_[4] = _011_[4];
  assign _063_[5] = _011_[5];
  assign _063_[6] = _011_[6];
  assign _063_[7] = _011_[7];
  assign _060_[3] = _128_;
  assign _064_[3] = _010_[3];
  assign _064_[4] = _011_[4];
  assign _064_[5] = _011_[5];
  assign _064_[6] = _011_[6];
  assign _064_[7] = _011_[7];
  assign _060_[4] = _129_;
  assign _065_[4] = _010_[4];
  assign _065_[5] = _011_[5];
  assign _065_[6] = _011_[6];
  assign _065_[7] = _011_[7];
  assign _060_[5] = _130_;
  assign _066_[5] = _010_[5];
  assign _066_[6] = _011_[6];
  assign _066_[7] = _011_[7];
  assign _060_[6] = _131_;
  assign _067_[6] = _010_[6];
  assign _067_[7] = _011_[7];
  assign _060_[7] = _132_;
  assign _068_ = _010_[7];
  assign _009_[9] = _161_;
  assign _069_[0] = _133_;
  assign _070_[0] = _010_[0];
  assign _070_[1] = _011_[1];
  assign _070_[2] = _011_[2];
  assign _070_[3] = _011_[3];
  assign _070_[4] = _011_[4];
  assign _070_[5] = _011_[5];
  assign _070_[6] = _011_[6];
  assign _070_[7] = _011_[7];
  assign _070_[8] = _011_[8];
  assign _069_[1] = _134_;
  assign _071_[1] = _010_[1];
  assign _071_[2] = _011_[2];
  assign _071_[3] = _011_[3];
  assign _071_[4] = _011_[4];
  assign _071_[5] = _011_[5];
  assign _071_[6] = _011_[6];
  assign _071_[7] = _011_[7];
  assign _071_[8] = _011_[8];
  assign _069_[2] = _135_;
  assign _072_[2] = _010_[2];
  assign _072_[3] = _011_[3];
  assign _072_[4] = _011_[4];
  assign _072_[5] = _011_[5];
  assign _072_[6] = _011_[6];
  assign _072_[7] = _011_[7];
  assign _072_[8] = _011_[8];
  assign _069_[3] = _136_;
  assign _073_[3] = _010_[3];
  assign _073_[4] = _011_[4];
  assign _073_[5] = _011_[5];
  assign _073_[6] = _011_[6];
  assign _073_[7] = _011_[7];
  assign _073_[8] = _011_[8];
  assign _069_[4] = _137_;
  assign _074_[4] = _010_[4];
  assign _074_[5] = _011_[5];
  assign _074_[6] = _011_[6];
  assign _074_[7] = _011_[7];
  assign _074_[8] = _011_[8];
  assign _069_[5] = _138_;
  assign _075_[5] = _010_[5];
  assign _075_[6] = _011_[6];
  assign _075_[7] = _011_[7];
  assign _075_[8] = _011_[8];
  assign _069_[6] = _139_;
  assign _076_[6] = _010_[6];
  assign _076_[7] = _011_[7];
  assign _076_[8] = _011_[8];
  assign _069_[7] = _140_;
  assign _077_[7] = _010_[7];
  assign _077_[8] = _011_[8];
  assign _069_[8] = _141_;
  assign _078_ = _010_[8];
  assign _009_[10] = _162_;
  assign _014_[0] = _142_;
  assign _015_[0] = _010_[0];
  assign _015_[1] = _011_[1];
  assign _015_[2] = _011_[2];
  assign _015_[3] = _011_[3];
  assign _015_[4] = _011_[4];
  assign _015_[5] = _011_[5];
  assign _015_[6] = _011_[6];
  assign _015_[7] = _011_[7];
  assign _015_[8] = _011_[8];
  assign _015_[9] = _011_[9];
  assign _014_[1] = _143_;
  assign _016_[1] = _010_[1];
  assign _016_[2] = _011_[2];
  assign _016_[3] = _011_[3];
  assign _016_[4] = _011_[4];
  assign _016_[5] = _011_[5];
  assign _016_[6] = _011_[6];
  assign _016_[7] = _011_[7];
  assign _016_[8] = _011_[8];
  assign _016_[9] = _011_[9];
  assign _014_[2] = _144_;
  assign _017_[2] = _010_[2];
  assign _017_[3] = _011_[3];
  assign _017_[4] = _011_[4];
  assign _017_[5] = _011_[5];
  assign _017_[6] = _011_[6];
  assign _017_[7] = _011_[7];
  assign _017_[8] = _011_[8];
  assign _017_[9] = _011_[9];
  assign _014_[3] = _145_;
  assign _018_[3] = _010_[3];
  assign _018_[4] = _011_[4];
  assign _018_[5] = _011_[5];
  assign _018_[6] = _011_[6];
  assign _018_[7] = _011_[7];
  assign _018_[8] = _011_[8];
  assign _018_[9] = _011_[9];
  assign _014_[4] = _146_;
  assign _019_[4] = _010_[4];
  assign _019_[5] = _011_[5];
  assign _019_[6] = _011_[6];
  assign _019_[7] = _011_[7];
  assign _019_[8] = _011_[8];
  assign _019_[9] = _011_[9];
  assign _014_[5] = _147_;
  assign _020_[5] = _010_[5];
  assign _020_[6] = _011_[6];
  assign _020_[7] = _011_[7];
  assign _020_[8] = _011_[8];
  assign _020_[9] = _011_[9];
  assign _014_[6] = _148_;
  assign _021_[6] = _010_[6];
  assign _021_[7] = _011_[7];
  assign _021_[8] = _011_[8];
  assign _021_[9] = _011_[9];
  assign _014_[7] = _149_;
  assign _022_[7] = _010_[7];
  assign _022_[8] = _011_[8];
  assign _022_[9] = _011_[9];
  assign _014_[8] = _150_;
  assign _023_[8] = _010_[8];
  assign _023_[9] = _011_[9];
  assign _014_[9] = _151_;
  assign _024_ = _010_[9];
endmodule
