/* Generated by Yosys 0.45 (git sha1 9ed031ddd, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* cells_not_processed =  1  *)
(* src = "counter.v:1.1-39.10" *)
module counter(clk, rst, mode, cnt);
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _000_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _001_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _002_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _003_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _004_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _005_;
  wire [4:0] _006_;
  wire [1:0] _007_;
  wire _008_;
  wire [4:0] _009_;
  wire [1:0] _010_;
  wire _011_;
  wire [4:0] _012_;
  wire [1:0] _013_;
  wire _014_;
  wire [4:0] _015_;
  wire [1:0] _016_;
  wire _017_;
  wire [4:0] _018_;
  wire [1:0] _019_;
  wire _020_;
  wire [4:0] _021_;
  wire [1:0] _022_;
  wire _023_;
  (* src = "counter.v:13.17-13.32" *)
  wire _024_;
  (* src = "counter.v:22.17-22.31" *)
  wire _025_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "9" *)
  wire [9:0] _026_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:270.23-270.24" *)
  wire [9:0] _027_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:270.26-270.27" *)
  wire [9:0] _028_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:214.23-214.24" *)
  (* unused_bits = "9" *)
  wire [9:0] _029_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.21-279.23" *)
  wire [9:0] _030_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "4 5 6" *)
  wire [9:0] _031_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "3 4 5 6 7 8" *)
  wire [9:0] _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 4 5 6" *)
  wire [9:0] _036_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "1 2 3 4 5 6 7 8" *)
  wire [9:0] _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 4 5 6" *)
  wire [9:0] _041_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "1 2 3 4 5 6 7 8" *)
  wire [9:0] _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 4 5 6" *)
  wire [9:0] _048_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "2 3 4 5 6 7 8" *)
  wire [9:0] _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _055_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _056_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _057_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _058_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _059_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _060_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _061_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _062_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _063_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _064_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _065_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _066_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _067_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _068_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _069_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _070_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _071_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _072_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _073_;
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _074_;
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _075_;
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _076_;
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _077_;
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _078_;
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _079_;
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _080_;
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _081_;
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _082_;
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _083_;
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _084_;
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _085_;
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _086_;
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _087_;
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _088_;
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _089_;
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _090_;
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _091_;
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _092_;
  (* src = "counter.v:3.17-3.20" *)
  input clk;
  wire clk;
  (* init = 10'h3ce *)
  (* src = "counter.v:6.29-6.32" *)
  output [9:0] cnt;
  wire [9:0] cnt;
  (* src = "counter.v:5.17-5.21" *)
  input mode;
  wire mode;
  (* src = "counter.v:4.17-4.20" *)
  input rst;
  wire rst;
  (* src = "counter.v:8.22-8.29" *)
  wire [9:0] summand;
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP0_  \cnt_reg[0]  /* _093_ */ (
    .C(clk),
    .D(_027_[0]),
    .Q(cnt[0]),
    .R(rst)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP1_  \cnt_reg[1]  /* _094_ */ (
    .C(clk),
    .D(_028_[1]),
    .Q(cnt[1]),
    .R(rst)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP1_  \cnt_reg[2]  /* _095_ */ (
    .C(clk),
    .D(_028_[2]),
    .Q(cnt[2]),
    .R(rst)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP1_  \cnt_reg[3]  /* _096_ */ (
    .C(clk),
    .D(_028_[3]),
    .Q(cnt[3]),
    .R(rst)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP0_  \cnt_reg[4]  /* _097_ */ (
    .C(clk),
    .D(_028_[4]),
    .Q(cnt[4]),
    .R(rst)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP0_  \cnt_reg[5]  /* _098_ */ (
    .C(clk),
    .D(_028_[5]),
    .Q(cnt[5]),
    .R(rst)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP1_  \cnt_reg[6]  /* _099_ */ (
    .C(clk),
    .D(_028_[6]),
    .Q(cnt[6]),
    .R(rst)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP1_  \cnt_reg[7]  /* _100_ */ (
    .C(clk),
    .D(_028_[7]),
    .Q(cnt[7]),
    .R(rst)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP1_  \cnt_reg[8]  /* _101_ */ (
    .C(clk),
    .D(_028_[8]),
    .Q(cnt[8]),
    .R(rst)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP1_  \cnt_reg[9]  /* _102_ */ (
    .C(clk),
    .D(_028_[9]),
    .Q(cnt[9]),
    .R(rst)
  );
  \$_NOT_  _103_ (
    .A(cnt[0]),
    .Y(_030_[0])
  );
  (* src = "counter.v:13.17-13.32" *)
  \$_OR_  _104_ (
    .A(cnt[0]),
    .B(cnt[1]),
    .Y(_006_[0])
  );
  (* src = "counter.v:13.17-13.32" *)
  \$_OR_  _105_ (
    .A(cnt[2]),
    .B(cnt[3]),
    .Y(_006_[1])
  );
  (* src = "counter.v:13.17-13.32" *)
  \$_OR_  _106_ (
    .A(_006_[0]),
    .B(_006_[1]),
    .Y(_007_[0])
  );
  (* src = "counter.v:13.17-13.32" *)
  \$_OR_  _107_ (
    .A(_007_[0]),
    .B(_007_[1]),
    .Y(_008_)
  );
  (* src = "counter.v:13.17-13.32" *)
  \$_OR_  _108_ (
    .A(_008_),
    .B(_006_[4]),
    .Y(_024_)
  );
  (* src = "counter.v:22.17-22.31" *)
  \$_OR_  _109_ (
    .A(cnt[0]),
    .B(_030_[1]),
    .Y(_009_[0])
  );
  (* src = "counter.v:22.17-22.31" *)
  \$_OR_  _110_ (
    .A(_030_[2]),
    .B(_030_[3]),
    .Y(_009_[1])
  );
  (* src = "counter.v:22.17-22.31" *)
  \$_OR_  _111_ (
    .A(_030_[4]),
    .B(_030_[5]),
    .Y(_006_[2])
  );
  (* src = "counter.v:22.17-22.31" *)
  \$_OR_  _112_ (
    .A(_030_[6]),
    .B(_030_[7]),
    .Y(_006_[3])
  );
  (* src = "counter.v:22.17-22.31" *)
  \$_OR_  _113_ (
    .A(_030_[8]),
    .B(_030_[9]),
    .Y(_006_[4])
  );
  (* src = "counter.v:22.17-22.31" *)
  \$_OR_  _114_ (
    .A(_009_[0]),
    .B(_009_[1]),
    .Y(_010_[0])
  );
  (* src = "counter.v:22.17-22.31" *)
  \$_OR_  _115_ (
    .A(_006_[2]),
    .B(_006_[3]),
    .Y(_007_[1])
  );
  (* src = "counter.v:22.17-22.31" *)
  \$_OR_  _116_ (
    .A(_010_[0]),
    .B(_007_[1]),
    .Y(_011_)
  );
  (* src = "counter.v:22.17-22.31" *)
  \$_OR_  _117_ (
    .A(_011_),
    .B(_006_[4]),
    .Y(_025_)
  );
  (* src = "counter.v:14.21-14.36" *)
  \$_AND_  _118_ (
    .A(_012_[0]),
    .B(_012_[1]),
    .Y(_013_[0])
  );
  (* src = "counter.v:14.21-14.36" *)
  \$_AND_  _119_ (
    .A(_013_[0]),
    .B(_013_[1]),
    .Y(_014_)
  );
  (* src = "counter.v:14.21-14.36" *)
  \$_AND_  _120_ (
    .A(_014_),
    .B(_012_[4]),
    .Y(_044_)
  );
  (* src = {0{1'b0}} *)
  \$_OR_  _121_ (
    .A(_043_),
    .B(_044_),
    .Y(_001_[2])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36" *)
  \$_AND_  _122_ (
    .A(cnt[0]),
    .B(_030_[1]),
    .Y(_015_[0])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36" *)
  \$_AND_  _123_ (
    .A(_015_[0]),
    .B(_031_[3]),
    .Y(_016_[0])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36" *)
  \$_AND_  _124_ (
    .A(_016_[0]),
    .B(_013_[1]),
    .Y(_017_)
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36" *)
  \$_AND_  _125_ (
    .A(_017_),
    .B(_012_[4]),
    .Y(_051_)
  );
  (* src = {0{1'b0}} *)
  \$_OR_  _126_ (
    .A(_035_),
    .B(_033_),
    .Y(_004_[9])
  );
  (* src = {0{1'b0}} *)
  \$_OR_  _127_ (
    .A(_040_),
    .B(_038_),
    .Y(_005_[9])
  );
  (* src = {0{1'b0}} *)
  \$_OR_  _128_ (
    .A(_050_),
    .B(_051_),
    .Y(_002_[3])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37" *)
  \$_AND_  _129_ (
    .A(_019_[0]),
    .B(_019_[1]),
    .Y(_020_)
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37" *)
  \$_AND_  _130_ (
    .A(_020_),
    .B(_018_[4]),
    .Y(_038_)
  );
  (* src = "counter.v:23.21-23.37" *)
  \$_AND_  _131_ (
    .A(cnt[0]),
    .B(cnt[1]),
    .Y(_021_[0])
  );
  (* src = "counter.v:23.21-23.37" *)
  \$_AND_  _132_ (
    .A(_021_[0]),
    .B(_031_[3]),
    .Y(_022_[0])
  );
  (* src = "counter.v:23.21-23.37" *)
  \$_AND_  _133_ (
    .A(_022_[0]),
    .B(_019_[1]),
    .Y(_023_)
  );
  (* src = "counter.v:23.21-23.37" *)
  \$_AND_  _134_ (
    .A(_023_),
    .B(_018_[4]),
    .Y(_033_)
  );
  (* src = "counter.v:22.17-22.31|counter.v:22.13-28.16" *)
  \$_AND_  _135_ (
    .A(_025_),
    .B(_004_[9]),
    .Y(_003_[4])
  );
  (* src = "counter.v:22.17-22.31|counter.v:22.13-28.16" *)
  \$_MUX_  _136_ (
    .A(_005_[9]),
    .B(_004_[9]),
    .S(_025_),
    .Y(_003_[9])
  );
  (* src = "counter.v:22.17-22.31|counter.v:22.13-28.16" *)
  \$_MUX_  _137_ (
    .A(_005_[9]),
    .B(1'h0),
    .S(_025_),
    .Y(_003_[3])
  );
  (* src = "counter.v:13.17-13.32|counter.v:13.13-19.16" *)
  \$_AND_  _138_ (
    .A(_024_),
    .B(_001_[2]),
    .Y(_000_[2])
  );
  (* src = "counter.v:13.17-13.32|counter.v:13.13-19.16" *)
  \$_MUX_  _139_ (
    .A(_002_[3]),
    .B(1'h0),
    .S(_024_),
    .Y(_000_[3])
  );
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$_MUX_  _140_ (
    .A(_003_[4]),
    .B(_000_[2]),
    .S(mode),
    .Y(summand[0])
  );
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$_MUX_  _141_ (
    .A(_003_[9]),
    .B(_000_[3]),
    .S(mode),
    .Y(summand[1])
  );
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$_MUX_  _142_ (
    .A(_003_[9]),
    .B(_000_[2]),
    .S(mode),
    .Y(summand[2])
  );
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$_MUX_  _143_ (
    .A(_003_[3]),
    .B(_000_[3]),
    .S(mode),
    .Y(summand[3])
  );
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$_MUX_  _144_ (
    .A(_003_[4]),
    .B(1'h0),
    .S(mode),
    .Y(summand[4])
  );
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$_MUX_  _145_ (
    .A(_003_[9]),
    .B(1'h0),
    .S(mode),
    .Y(summand[9])
  );
  (* src = "counter.v:14.21-14.36" *)
  \$_NOT_  _146_ (
    .A(_045_),
    .Y(_043_)
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36" *)
  \$_NOT_  _147_ (
    .A(_052_),
    .Y(_050_)
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _148_ (
    .A(cnt[9]),
    .Y(_030_[9])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _149_ (
    .A(cnt[1]),
    .Y(_030_[1])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _150_ (
    .A(cnt[2]),
    .Y(_030_[2])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _151_ (
    .A(cnt[3]),
    .Y(_030_[3])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _152_ (
    .A(cnt[4]),
    .Y(_030_[4])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _153_ (
    .A(cnt[5]),
    .Y(_030_[5])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _154_ (
    .A(cnt[6]),
    .Y(_030_[6])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _155_ (
    .A(cnt[7]),
    .Y(_030_[7])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _156_ (
    .A(cnt[8]),
    .Y(_030_[8])
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _157_ (
    .A(_041_[9]),
    .B(_041_[8]),
    .Y(_046_)
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _158_ (
    .A(_046_),
    .B(_042_[9]),
    .Y(_047_)
  );
  (* src = {0{1'b0}} *)
  \$_OR_  _159_ (
    .A(_047_),
    .B(_044_),
    .Y(_045_)
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _160_ (
    .A(_053_),
    .B(_049_[9]),
    .Y(_054_)
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _161_ (
    .A(_048_[9]),
    .B(_048_[8]),
    .Y(_053_)
  );
  (* src = {0{1'b0}} *)
  \$_OR_  _162_ (
    .A(_054_),
    .B(_051_),
    .Y(_052_)
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _163_ (
    .A(_031_[9]),
    .B(_031_[8]),
    .Y(_034_)
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _164_ (
    .A(_034_),
    .B(_032_[9]),
    .Y(_035_)
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _165_ (
    .A(_036_[9]),
    .B(_036_[8]),
    .Y(_039_)
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _166_ (
    .A(_039_),
    .B(_037_[9]),
    .Y(_040_)
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _167_ (
    .A(cnt[9]),
    .B(_036_[8]),
    .Y(_037_[9])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _168_ (
    .A(cnt[9]),
    .B(_031_[8]),
    .Y(_032_[9])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _169_ (
    .A(_030_[9]),
    .B(_048_[8]),
    .Y(_049_[9])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _170_ (
    .A(_027_[1]),
    .B(_026_[0]),
    .Y(_028_[1])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _171_ (
    .A(_027_[2]),
    .B(_026_[1]),
    .Y(_028_[2])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _172_ (
    .A(_027_[3]),
    .B(_026_[2]),
    .Y(_028_[3])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _173_ (
    .A(_027_[4]),
    .B(_026_[3]),
    .Y(_028_[4])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _174_ (
    .A(_027_[5]),
    .B(_026_[4]),
    .Y(_028_[5])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _175_ (
    .A(_027_[6]),
    .B(_026_[5]),
    .Y(_028_[6])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _176_ (
    .A(_027_[7]),
    .B(_026_[6]),
    .Y(_028_[7])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _177_ (
    .A(_027_[8]),
    .B(_026_[7]),
    .Y(_028_[8])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _178_ (
    .A(_027_[9]),
    .B(_026_[8]),
    .Y(_028_[9])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:288.13-288.20" *)
  \$_XOR_  _179_ (
    .A(summand[0]),
    .B(cnt[0]),
    .Y(_027_[0])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:288.13-288.20" *)
  \$_XOR_  _180_ (
    .A(summand[1]),
    .B(cnt[1]),
    .Y(_027_[1])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:288.13-288.20" *)
  \$_XOR_  _181_ (
    .A(summand[2]),
    .B(cnt[2]),
    .Y(_027_[2])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:288.13-288.20" *)
  \$_XOR_  _182_ (
    .A(summand[3]),
    .B(cnt[3]),
    .Y(_027_[3])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:288.13-288.20" *)
  \$_XOR_  _183_ (
    .A(summand[4]),
    .B(cnt[4]),
    .Y(_027_[4])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:288.13-288.20" *)
  \$_XOR_  _184_ (
    .A(summand[9]),
    .B(cnt[5]),
    .Y(_027_[5])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:288.13-288.20" *)
  \$_XOR_  _185_ (
    .A(summand[9]),
    .B(cnt[6]),
    .Y(_027_[6])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:288.13-288.20" *)
  \$_XOR_  _186_ (
    .A(summand[9]),
    .B(cnt[7]),
    .Y(_027_[7])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:288.13-288.20" *)
  \$_XOR_  _187_ (
    .A(summand[9]),
    .B(cnt[8]),
    .Y(_027_[8])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:288.13-288.20" *)
  \$_XOR_  _188_ (
    .A(summand[9]),
    .B(cnt[9]),
    .Y(_027_[9])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.42-286.49" *)
  \$_AND_  _189_ (
    .A(summand[0]),
    .B(cnt[0]),
    .Y(_026_[0])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.42-286.49" *)
  \$_AND_  _190_ (
    .A(summand[1]),
    .B(cnt[1]),
    .Y(_029_[1])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.42-286.49" *)
  \$_AND_  _191_ (
    .A(summand[2]),
    .B(cnt[2]),
    .Y(_029_[2])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.42-286.49" *)
  \$_AND_  _192_ (
    .A(summand[3]),
    .B(cnt[3]),
    .Y(_029_[3])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.42-286.49" *)
  \$_AND_  _193_ (
    .A(summand[4]),
    .B(cnt[4]),
    .Y(_029_[4])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.42-286.49" *)
  \$_AND_  _194_ (
    .A(summand[9]),
    .B(cnt[5]),
    .Y(_029_[5])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.42-286.49" *)
  \$_AND_  _195_ (
    .A(summand[9]),
    .B(cnt[6]),
    .Y(_029_[6])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.42-286.49" *)
  \$_AND_  _196_ (
    .A(summand[9]),
    .B(cnt[7]),
    .Y(_029_[7])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.42-286.49" *)
  \$_AND_  _197_ (
    .A(summand[9]),
    .B(cnt[8]),
    .Y(_029_[8])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _198_ (
    .A(_030_[9]),
    .B(_041_[8]),
    .Y(_042_[9])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _199_ (
    .A(cnt[3]),
    .B(_030_[2]),
    .Y(_081_)
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _200_ (
    .A(cnt[8]),
    .B(_031_[7]),
    .Y(_079_)
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _201_ (
    .A(_030_[1]),
    .B(_030_[0]),
    .Y(_036_[1])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _202_ (
    .A(_019_[1]),
    .B(_036_[3]),
    .Y(_082_)
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _203_ (
    .A(cnt[3]),
    .B(cnt[2]),
    .Y(_018_[1])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _204_ (
    .A(_030_[3]),
    .B(_081_),
    .Y(_085_)
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _205_ (
    .A(_027_[6]),
    .B(_026_[5]),
    .Y(_069_)
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _206_ (
    .A(cnt[1]),
    .B(_030_[0]),
    .Y(_012_[0])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _207_ (
    .A(_018_[3]),
    .B(_012_[2]),
    .Y(_019_[1])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _208_ (
    .A(_091_),
    .B(_092_),
    .Y(_048_[7])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _209_ (
    .A(_012_[3]),
    .B(_012_[2]),
    .Y(_013_[1])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _210_ (
    .A(cnt[7]),
    .B(cnt[6]),
    .Y(_012_[3])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _211_ (
    .A(_018_[1]),
    .B(_036_[1]),
    .Y(_019_[0])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _212_ (
    .A(_013_[1]),
    .B(_041_[3]),
    .Y(_089_)
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _213_ (
    .A(_012_[1]),
    .B(_041_[1]),
    .Y(_087_)
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _214_ (
    .A(_030_[3]),
    .B(cnt[2]),
    .Y(_012_[1])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _215_ (
    .A(_012_[3]),
    .B(_030_[5]),
    .Y(_088_)
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _216_ (
    .A(_030_[1]),
    .B(_012_[0]),
    .Y(_041_[1])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _217_ (
    .A(_012_[4]),
    .B(_041_[7]),
    .Y(_041_[9])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _218_ (
    .A(_030_[8]),
    .B(_041_[7]),
    .Y(_041_[8])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _219_ (
    .A(_030_[9]),
    .B(_030_[8]),
    .Y(_012_[4])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _220_ (
    .A(cnt[7]),
    .B(_030_[6]),
    .Y(_086_)
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _221_ (
    .A(_013_[1]),
    .B(_048_[3]),
    .Y(_092_)
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _222_ (
    .A(_031_[3]),
    .B(_030_[1]),
    .Y(_048_[3])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _223_ (
    .A(_031_[3]),
    .B(_087_),
    .Y(_041_[3])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _224_ (
    .A(_091_),
    .B(_089_),
    .Y(_041_[7])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _225_ (
    .A(_018_[4]),
    .B(_036_[7]),
    .Y(_083_)
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.12-248.41" *)
  \$_OR_  _226_ (
    .A(_029_[8]),
    .B(_070_),
    .Y(_026_[8])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.12-248.41" *)
  \$_OR_  _227_ (
    .A(_029_[6]),
    .B(_069_),
    .Y(_026_[6])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _228_ (
    .A(_090_),
    .B(_088_),
    .Y(_091_)
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _229_ (
    .A(_012_[4]),
    .B(_048_[7]),
    .Y(_048_[9])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.12-248.41" *)
  \$_OR_  _230_ (
    .A(_072_),
    .B(_066_),
    .Y(_026_[5])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _231_ (
    .A(_029_[3]),
    .B(_056_),
    .Y(_071_)
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _232_ (
    .A(_018_[4]),
    .B(_031_[7]),
    .Y(_078_)
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.12-248.41" *)
  \$_OR_  _233_ (
    .A(_080_),
    .B(_078_),
    .Y(_031_[9])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _234_ (
    .A(_027_[1]),
    .B(_026_[0]),
    .Y(_055_)
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _235_ (
    .A(_027_[3]),
    .B(_029_[2]),
    .Y(_056_)
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _236_ (
    .A(_027_[5]),
    .B(_029_[4]),
    .Y(_057_)
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _237_ (
    .A(_027_[7]),
    .B(_029_[6]),
    .Y(_058_)
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.12-248.41" *)
  \$_OR_  _238_ (
    .A(_030_[8]),
    .B(_084_),
    .Y(_036_[8])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.12-248.41" *)
  \$_OR_  _239_ (
    .A(_029_[2]),
    .B(_067_),
    .Y(_026_[2])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _240_ (
    .A(_029_[7]),
    .B(_058_),
    .Y(_073_)
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _241_ (
    .A(_029_[5]),
    .B(_057_),
    .Y(_072_)
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.12-248.41" *)
  \$_OR_  _242_ (
    .A(_029_[4]),
    .B(_068_),
    .Y(_026_[4])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _243_ (
    .A(cnt[8]),
    .B(_036_[7]),
    .Y(_084_)
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _244_ (
    .A(cnt[9]),
    .B(cnt[8]),
    .Y(_018_[4])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _245_ (
    .A(_071_),
    .B(_059_),
    .Y(_026_[3])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _246_ (
    .A(_030_[7]),
    .B(_086_),
    .Y(_090_)
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.12-248.41" *)
  \$_OR_  _247_ (
    .A(_080_),
    .B(_083_),
    .Y(_036_[9])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _248_ (
    .A(_030_[7]),
    .B(_030_[6]),
    .Y(_018_[3])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _249_ (
    .A(_030_[8]),
    .B(_048_[7]),
    .Y(_048_[8])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _250_ (
    .A(_073_),
    .B(_060_),
    .Y(_074_)
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _251_ (
    .A(_074_),
    .B(_061_),
    .Y(_026_[7])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _252_ (
    .A(_029_[1]),
    .B(_055_),
    .Y(_026_[1])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _253_ (
    .A(_076_),
    .B(_082_),
    .Y(_036_[7])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _254_ (
    .A(cnt[5]),
    .B(_030_[4]),
    .Y(_012_[2])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _255_ (
    .A(_030_[3]),
    .B(_030_[2]),
    .Y(_031_[3])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.12-248.41" *)
  \$_OR_  _256_ (
    .A(_030_[8]),
    .B(_079_),
    .Y(_031_[8])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _257_ (
    .A(_019_[1]),
    .B(_031_[3]),
    .Y(_077_)
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _258_ (
    .A(_018_[3]),
    .B(_030_[5]),
    .Y(_076_)
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _259_ (
    .A(_027_[8]),
    .B(_026_[7]),
    .Y(_070_)
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _260_ (
    .A(_030_[9]),
    .B(_075_),
    .Y(_080_)
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _261_ (
    .A(_085_),
    .B(_019_[0]),
    .Y(_036_[3])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _262_ (
    .A(cnt[9]),
    .B(_030_[8]),
    .Y(_075_)
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _263_ (
    .A(_076_),
    .B(_077_),
    .Y(_031_[7])
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _264_ (
    .A(_062_),
    .B(_026_[1]),
    .Y(_059_)
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _265_ (
    .A(_064_),
    .B(_072_),
    .Y(_060_)
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _266_ (
    .A(_065_),
    .B(_026_[3]),
    .Y(_061_)
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _267_ (
    .A(_027_[3]),
    .B(_027_[2]),
    .Y(_062_)
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _268_ (
    .A(_027_[5]),
    .B(_027_[4]),
    .Y(_063_)
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _269_ (
    .A(_027_[7]),
    .B(_027_[6]),
    .Y(_064_)
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _270_ (
    .A(_064_),
    .B(_063_),
    .Y(_065_)
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _271_ (
    .A(_063_),
    .B(_026_[3]),
    .Y(_066_)
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _272_ (
    .A(_027_[2]),
    .B(_026_[1]),
    .Y(_067_)
  );
  (* src = "counter.v:36.20-36.33|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _273_ (
    .A(_027_[4]),
    .B(_026_[3]),
    .Y(_068_)
  );
  assign { _000_[9:4], _000_[1:0] } = { 6'h00, _000_[3:2] };
  assign { _001_[9:3], _001_[1:0] } = { 8'h00, _001_[2] };
  assign { _002_[9:4], _002_[2:0] } = { 7'h00, _002_[3], 1'h0 };
  assign { _003_[8:5], _003_[2:0] } = { _003_[9], _003_[9], _003_[9], _003_[9], _003_[9], _003_[9], _003_[4] };
  assign _004_[8:0] = { _004_[9], _004_[9], _004_[9], _004_[9], _004_[9], 1'h0, _004_[9], _004_[9], _004_[9] };
  assign _005_[8:0] = { _005_[9], _005_[9], _005_[9], _005_[9], 1'h0, _005_[9], _005_[9], _005_[9], 1'h0 };
  assign _009_[4:2] = _006_[4:2];
  assign _010_[1] = _007_[1];
  assign _015_[4:1] = { _012_[4:2], _031_[3] };
  assign _016_[1] = _013_[1];
  assign { _018_[2], _018_[0] } = { _012_[2], _036_[1] };
  assign _021_[4:1] = { _018_[4:3], _012_[2], _031_[3] };
  assign _022_[1] = _019_[1];
  assign _028_[0] = _027_[0];
  assign _029_[0] = _026_[0];
  assign _031_[2:0] = { _030_[2], 2'h3 };
  assign _032_[2:0] = { cnt[2], _030_[1:0] };
  assign _036_[0] = _030_[0];
  assign _037_[0] = cnt[0];
  assign _041_[0] = _030_[0];
  assign _042_[0] = cnt[0];
  assign _048_[1:0] = { _030_[1], 1'h1 };
  assign _049_[1:0] = { cnt[1], _030_[0] };
  assign summand[8:5] = { summand[9], summand[9], summand[9], summand[9] };
endmodule
