/* Generated by Yosys 0.45 (git sha1 9ed031ddd, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* cells_not_processed =  1  *)
(* src = "counter.v:1.1-39.10" *)
module counter(clk, rst, mode, cnt);
  (* src = "counter.v:32.5-38.8" *)
  wire [9:0] _000_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _001_;
  (* src = "counter.v:6.29-6.43" *)
  wire [9:0] _002_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _003_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _004_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _005_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _006_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _007_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _008_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _009_;
  (* src = "counter.v:36.20-36.33|map.v:9.26-9.27" *)
  wire [9:0] _010_;
  (* src = "counter.v:36.20-36.33|map.v:10.26-10.27" *)
  wire [9:0] _011_;
  (* src = "counter.v:36.20-36.33|map.v:15.22-15.23" *)
  wire [10:0] _012_;
  (* src = "counter.v:36.20-36.33|map.v:13.22-13.23" *)
  wire [10:0] _013_;
  (* src = "counter.v:36.20-36.33|map.v:14.22-14.23" *)
  wire [10:0] _014_;
  (* src = "counter.v:36.20-36.33|map.v:11.26-11.27" *)
  wire [10:0] _015_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [-1:0] _016_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [9:0] _017_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [9:0] _018_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [9:1] _019_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [9:2] _020_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [9:3] _021_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [9:4] _022_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [9:5] _023_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [9:6] _024_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [9:7] _025_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [9:8] _026_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _027_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire _028_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _029_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [1:0] _030_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [1:0] _031_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _032_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [2:0] _033_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [2:0] _034_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [2:1] _035_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _036_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [3:0] _037_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [3:0] _038_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [3:1] _039_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [3:2] _040_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _041_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [4:0] _042_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [4:0] _043_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [4:1] _044_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [4:2] _045_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [4:3] _046_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _047_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [5:0] _048_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [5:0] _049_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [5:1] _050_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [5:2] _051_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [5:3] _052_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [5:4] _053_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _054_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [6:0] _055_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [6:0] _056_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [6:1] _057_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [6:2] _058_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [6:3] _059_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [6:4] _060_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [6:5] _061_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _062_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [7:0] _063_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [7:0] _064_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [7:1] _065_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [7:2] _066_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [7:3] _067_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [7:4] _068_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [7:5] _069_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [7:6] _070_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _071_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [8:0] _072_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [8:0] _073_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [8:1] _074_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [8:2] _075_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [8:3] _076_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [8:4] _077_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [8:5] _078_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [8:6] _079_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire [8:7] _080_;
  (* src = "counter.v:36.20-36.33|map.v:29.30-29.38" *)
  wire _081_;
  (* src = "counter.v:36.20-36.33" *)
  wire [9:0] _082_;
  (* src = "counter.v:23.21-23.37" *)
  wire _083_;
  (* src = "counter.v:26.26-26.42" *)
  wire _084_;
  (* src = "counter.v:14.21-14.36" *)
  wire _085_;
  (* src = "counter.v:17.26-17.41" *)
  wire _086_;
  (* src = "counter.v:13.17-13.32" *)
  wire _087_;
  (* src = "counter.v:22.17-22.31" *)
  wire _088_;
  wire [9:0] _089_;
  wire _090_;
  wire [9:0] _091_;
  wire _092_;
  wire [9:0] _093_;
  wire _094_;
  wire [9:0] _095_;
  wire _096_;
  wire [9:0] _097_;
  wire _098_;
  wire [9:0] _099_;
  wire _100_;
  wire [9:0] _101_;
  wire _102_;
  wire [9:0] _103_;
  wire _104_;
  wire [9:0] _105_;
  wire _106_;
  wire [9:0] _107_;
  wire _108_;
  wire [9:0] _109_;
  wire _110_;
  wire [9:0] _111_;
  wire _112_;
  wire [9:0] _113_;
  wire _114_;
  wire [9:0] _115_;
  wire _116_;
  wire [9:0] _117_;
  wire _118_;
  wire [9:0] _119_;
  wire _120_;
  wire [9:0] _121_;
  wire _122_;
  wire [9:0] _123_;
  wire _124_;
  (* src = "counter.v:36.20-36.33|map.v:39.16-39.21" *)
  wire [10:0] _125_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _126_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _127_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _128_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _129_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _130_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _131_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _132_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _133_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _134_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _135_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _136_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _137_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _138_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _139_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _140_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _141_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _142_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _143_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _144_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _145_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _146_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _147_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _148_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _149_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _150_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _151_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _152_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _153_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _154_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _155_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _156_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _157_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _158_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _159_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _160_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _161_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _162_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _163_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _164_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _165_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _166_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _167_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _168_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _169_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _170_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _171_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _172_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _173_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _174_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _175_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _176_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _177_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _178_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _179_;
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  wire _180_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _181_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _182_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _183_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _184_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _185_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _186_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _187_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _188_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _189_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _190_;
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  wire _191_;
  (* src = "counter.v:36.20-36.33|map.v:40.16-40.21" *)
  wire [10:0] _192_;
  (* src = "counter.v:36.20-36.33|map.v:44.29-44.60" *)
  wire [8:0] _193_;
  (* src = "counter.v:3.17-3.20" *)
  input clk;
  wire clk;
  (* init = 10'h3ce *)
  (* src = "counter.v:6.29-6.32" *)
  output [9:0] cnt;
  wire [9:0] cnt;
  (* src = "counter.v:5.17-5.21" *)
  input mode;
  wire mode;
  (* src = "counter.v:4.17-4.20" *)
  input rst;
  wire rst;
  (* src = "counter.v:8.22-8.29" *)
  wire [9:0] summand;
  (* src = "counter.v:23.21-23.37" *)
  \$ge  #(
    .A_SIGNED(32'd1),
    .A_WIDTH(32'd10),
    .B_SIGNED(32'd1),
    .B_WIDTH(32'd10),
    .Y_WIDTH(32'd1)
  ) _194_ (
    .A(cnt),
    .B(10'h323),
    .Y(_083_)
  );
  (* src = "counter.v:26.26-26.42" *)
  \$ge  #(
    .A_SIGNED(32'd1),
    .A_WIDTH(32'd10),
    .B_SIGNED(32'd1),
    .B_WIDTH(32'd10),
    .Y_WIDTH(32'd1)
  ) _195_ (
    .A(cnt),
    .B(10'h32c),
    .Y(_084_)
  );
  (* src = "counter.v:14.21-14.36" *)
  \$le  #(
    .A_SIGNED(32'd1),
    .A_WIDTH(32'd10),
    .B_SIGNED(32'd1),
    .B_WIDTH(32'd10),
    .Y_WIDTH(32'd1)
  ) _196_ (
    .A(cnt),
    .B(10'h0e6),
    .Y(_085_)
  );
  (* src = "counter.v:17.26-17.41" *)
  \$le  #(
    .A_SIGNED(32'd1),
    .A_WIDTH(32'd10),
    .B_SIGNED(32'd1),
    .B_WIDTH(32'd10),
    .Y_WIDTH(32'd1)
  ) _197_ (
    .A(cnt),
    .B(10'h0e1),
    .Y(_086_)
  );
  (* src = "counter.v:13.17-13.32" *)
  \$ne  #(
    .A_SIGNED(32'd1),
    .A_WIDTH(32'd10),
    .B_SIGNED(32'd1),
    .B_WIDTH(32'd10),
    .Y_WIDTH(32'd1)
  ) _198_ (
    .A(cnt),
    .B(10'h3f0),
    .Y(_087_)
  );
  (* src = "counter.v:22.17-22.31" *)
  \$ne  #(
    .A_SIGNED(32'd1),
    .A_WIDTH(32'd10),
    .B_SIGNED(32'd1),
    .B_WIDTH(32'd10),
    .Y_WIDTH(32'd1)
  ) _199_ (
    .A(cnt),
    .B(10'h3fe),
    .Y(_088_)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$dff  #(
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd10)
  ) _200_ (
    .CLK(clk),
    .D(_089_),
    .Q(cnt)
  );
  (* full_case = 32'd1 *)
  (* src = "counter.v:33.13-33.16|counter.v:33.9-37.12" *)
  \$mux  #(
    .WIDTH(32'd10)
  ) _201_ (
    .A(_082_),
    .B(10'h3ce),
    .S(_090_),
    .Y(_089_)
  );
  (* full_case = 32'd1 *)
  (* src = "counter.v:26.26-26.42|counter.v:26.22-28.16" *)
  \$mux  #(
    .WIDTH(32'd10)
  ) _202_ (
    .A(10'h000),
    .B(10'h3ee),
    .S(_092_),
    .Y(_091_)
  );
  (* full_case = 32'd1 *)
  (* src = "counter.v:22.17-22.31|counter.v:22.13-28.16" *)
  \$mux  #(
    .WIDTH(32'd10)
  ) _203_ (
    .A(_091_),
    .B(10'hxxx),
    .S(_094_),
    .Y(_093_)
  );
  (* full_case = 32'd1 *)
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$mux  #(
    .WIDTH(32'd10)
  ) _204_ (
    .A(_093_),
    .B(10'hxxx),
    .S(_096_),
    .Y(_095_)
  );
  (* full_case = 32'd1 *)
  (* src = "counter.v:23.21-23.37|counter.v:23.17-25.20" *)
  \$mux  #(
    .WIDTH(32'd10)
  ) _205_ (
    .A(10'h000),
    .B(10'h3f7),
    .S(_098_),
    .Y(_097_)
  );
  (* full_case = 32'd1 *)
  (* src = "counter.v:22.17-22.31|counter.v:22.13-28.16" *)
  \$mux  #(
    .WIDTH(32'd10)
  ) _206_ (
    .A(10'hxxx),
    .B(_097_),
    .S(_100_),
    .Y(_099_)
  );
  (* full_case = 32'd1 *)
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$mux  #(
    .WIDTH(32'd10)
  ) _207_ (
    .A(_099_),
    .B(10'hxxx),
    .S(_102_),
    .Y(_101_)
  );
  (* full_case = 32'd1 *)
  (* src = "counter.v:22.17-22.31|counter.v:22.13-28.16" *)
  \$mux  #(
    .WIDTH(32'd10)
  ) _208_ (
    .A(_009_),
    .B(_008_),
    .S(_104_),
    .Y(_103_)
  );
  (* full_case = 32'd1 *)
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$mux  #(
    .WIDTH(32'd10)
  ) _209_ (
    .A(_103_),
    .B(10'hxxx),
    .S(_106_),
    .Y(_105_)
  );
  (* full_case = 32'd1 *)
  (* src = "counter.v:17.26-17.41|counter.v:17.22-19.16" *)
  \$mux  #(
    .WIDTH(32'd10)
  ) _210_ (
    .A(10'h000),
    .B(10'h00a),
    .S(_108_),
    .Y(_107_)
  );
  (* full_case = 32'd1 *)
  (* src = "counter.v:13.17-13.32|counter.v:13.13-19.16" *)
  \$mux  #(
    .WIDTH(32'd10)
  ) _211_ (
    .A(_107_),
    .B(10'hxxx),
    .S(_110_),
    .Y(_109_)
  );
  (* full_case = 32'd1 *)
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$mux  #(
    .WIDTH(32'd10)
  ) _212_ (
    .A(10'hxxx),
    .B(_109_),
    .S(_112_),
    .Y(_111_)
  );
  (* full_case = 32'd1 *)
  (* src = "counter.v:14.21-14.36|counter.v:14.17-16.20" *)
  \$mux  #(
    .WIDTH(32'd10)
  ) _213_ (
    .A(10'h000),
    .B(10'h005),
    .S(_114_),
    .Y(_113_)
  );
  (* full_case = 32'd1 *)
  (* src = "counter.v:13.17-13.32|counter.v:13.13-19.16" *)
  \$mux  #(
    .WIDTH(32'd10)
  ) _214_ (
    .A(10'hxxx),
    .B(_113_),
    .S(_116_),
    .Y(_115_)
  );
  (* full_case = 32'd1 *)
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$mux  #(
    .WIDTH(32'd10)
  ) _215_ (
    .A(10'hxxx),
    .B(_115_),
    .S(_118_),
    .Y(_117_)
  );
  (* full_case = 32'd1 *)
  (* src = "counter.v:13.17-13.32|counter.v:13.13-19.16" *)
  \$mux  #(
    .WIDTH(32'd10)
  ) _216_ (
    .A(_006_),
    .B(_005_),
    .S(_120_),
    .Y(_119_)
  );
  (* full_case = 32'd1 *)
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$mux  #(
    .WIDTH(32'd10)
  ) _217_ (
    .A(10'hxxx),
    .B(_119_),
    .S(_122_),
    .Y(_121_)
  );
  (* full_case = 32'd1 *)
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$mux  #(
    .WIDTH(32'd10)
  ) _218_ (
    .A(_007_),
    .B(_004_),
    .S(_124_),
    .Y(_123_)
  );
  (* src = "counter.v:36.20-36.33|map.v:39.16-39.21" *)
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd10),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd10),
    .Y_WIDTH(32'd11)
  ) _219_ (
    .A(cnt),
    .B(summand),
    .Y(_125_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _220_ (
    .A(_029_),
    .Y(_126_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _221_ (
    .A(_031_),
    .Y(_127_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _222_ (
    .A(_032_),
    .Y(_128_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _223_ (
    .A(_034_),
    .Y(_129_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _224_ (
    .A(_035_),
    .Y(_130_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _225_ (
    .A(_036_),
    .Y(_131_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd4),
    .Y_WIDTH(32'd1)
  ) _226_ (
    .A(_038_),
    .Y(_132_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _227_ (
    .A(_039_),
    .Y(_133_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _228_ (
    .A(_040_),
    .Y(_134_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _229_ (
    .A(_041_),
    .Y(_135_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd5),
    .Y_WIDTH(32'd1)
  ) _230_ (
    .A(_043_),
    .Y(_136_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd4),
    .Y_WIDTH(32'd1)
  ) _231_ (
    .A(_044_),
    .Y(_137_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _232_ (
    .A(_045_),
    .Y(_138_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _233_ (
    .A(_046_),
    .Y(_139_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _234_ (
    .A(_047_),
    .Y(_140_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .Y_WIDTH(32'd1)
  ) _235_ (
    .A(_049_),
    .Y(_141_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd5),
    .Y_WIDTH(32'd1)
  ) _236_ (
    .A(_050_),
    .Y(_142_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd4),
    .Y_WIDTH(32'd1)
  ) _237_ (
    .A(_051_),
    .Y(_143_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _238_ (
    .A(_052_),
    .Y(_144_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _239_ (
    .A(_053_),
    .Y(_145_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _240_ (
    .A(_054_),
    .Y(_146_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd7),
    .Y_WIDTH(32'd1)
  ) _241_ (
    .A(_056_),
    .Y(_147_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .Y_WIDTH(32'd1)
  ) _242_ (
    .A(_057_),
    .Y(_148_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd5),
    .Y_WIDTH(32'd1)
  ) _243_ (
    .A(_058_),
    .Y(_149_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd4),
    .Y_WIDTH(32'd1)
  ) _244_ (
    .A(_059_),
    .Y(_150_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _245_ (
    .A(_060_),
    .Y(_151_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _246_ (
    .A(_061_),
    .Y(_152_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _247_ (
    .A(_062_),
    .Y(_153_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd8),
    .Y_WIDTH(32'd1)
  ) _248_ (
    .A(_064_),
    .Y(_154_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd7),
    .Y_WIDTH(32'd1)
  ) _249_ (
    .A(_065_),
    .Y(_155_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .Y_WIDTH(32'd1)
  ) _250_ (
    .A(_066_),
    .Y(_156_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd5),
    .Y_WIDTH(32'd1)
  ) _251_ (
    .A(_067_),
    .Y(_157_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd4),
    .Y_WIDTH(32'd1)
  ) _252_ (
    .A(_068_),
    .Y(_158_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _253_ (
    .A(_069_),
    .Y(_159_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _254_ (
    .A(_070_),
    .Y(_160_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _255_ (
    .A(_071_),
    .Y(_161_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd9),
    .Y_WIDTH(32'd1)
  ) _256_ (
    .A(_073_),
    .Y(_162_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd8),
    .Y_WIDTH(32'd1)
  ) _257_ (
    .A(_074_),
    .Y(_163_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd7),
    .Y_WIDTH(32'd1)
  ) _258_ (
    .A(_075_),
    .Y(_164_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .Y_WIDTH(32'd1)
  ) _259_ (
    .A(_076_),
    .Y(_165_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd5),
    .Y_WIDTH(32'd1)
  ) _260_ (
    .A(_077_),
    .Y(_166_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd4),
    .Y_WIDTH(32'd1)
  ) _261_ (
    .A(_078_),
    .Y(_167_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _262_ (
    .A(_079_),
    .Y(_168_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _263_ (
    .A(_080_),
    .Y(_169_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _264_ (
    .A(_081_),
    .Y(_170_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd10),
    .Y_WIDTH(32'd1)
  ) _265_ (
    .A(_018_),
    .Y(_171_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd9),
    .Y_WIDTH(32'd1)
  ) _266_ (
    .A(_019_),
    .Y(_172_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd8),
    .Y_WIDTH(32'd1)
  ) _267_ (
    .A(_020_),
    .Y(_173_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd7),
    .Y_WIDTH(32'd1)
  ) _268_ (
    .A(_021_),
    .Y(_174_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .Y_WIDTH(32'd1)
  ) _269_ (
    .A(_022_),
    .Y(_175_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd5),
    .Y_WIDTH(32'd1)
  ) _270_ (
    .A(_023_),
    .Y(_176_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd4),
    .Y_WIDTH(32'd1)
  ) _271_ (
    .A(_024_),
    .Y(_177_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _272_ (
    .A(_025_),
    .Y(_178_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _273_ (
    .A(_026_),
    .Y(_179_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _274_ (
    .A(_027_),
    .Y(_180_)
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$reduce_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _275_ (
    .A(_016_),
    .Y(_181_)
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$reduce_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _276_ (
    .A(_028_),
    .Y(_182_)
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$reduce_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _277_ (
    .A(_030_),
    .Y(_183_)
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$reduce_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _278_ (
    .A(_033_),
    .Y(_184_)
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$reduce_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd4),
    .Y_WIDTH(32'd1)
  ) _279_ (
    .A(_037_),
    .Y(_185_)
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$reduce_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd5),
    .Y_WIDTH(32'd1)
  ) _280_ (
    .A(_042_),
    .Y(_186_)
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$reduce_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .Y_WIDTH(32'd1)
  ) _281_ (
    .A(_048_),
    .Y(_187_)
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$reduce_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd7),
    .Y_WIDTH(32'd1)
  ) _282_ (
    .A(_055_),
    .Y(_188_)
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$reduce_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd8),
    .Y_WIDTH(32'd1)
  ) _283_ (
    .A(_063_),
    .Y(_189_)
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$reduce_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd9),
    .Y_WIDTH(32'd1)
  ) _284_ (
    .A(_072_),
    .Y(_190_)
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$reduce_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd10),
    .Y_WIDTH(32'd1)
  ) _285_ (
    .A(_017_),
    .Y(_191_)
  );
  (* src = "counter.v:36.20-36.33|map.v:40.16-40.21" *)
  \$xor  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd10),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd10),
    .Y_WIDTH(32'd11)
  ) _286_ (
    .A(cnt),
    .B(summand),
    .Y(_192_)
  );
  (* src = "counter.v:36.20-36.33|map.v:44.29-44.60" *)
  \$xor  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd9),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd9),
    .Y_WIDTH(32'd9)
  ) _287_ (
    .A(_014_[9:1]),
    .B(_012_[9:1]),
    .Y(_193_)
  );
  assign _002_ = 10'h3ce;
  assign _001_ = _003_;
  assign _090_ = rst;
  assign _000_ = _089_;
  assign _092_ = _084_;
  assign _094_ = _088_;
  assign _096_ = mode;
  assign _009_ = _095_;
  assign _098_ = _083_;
  assign _100_ = _088_;
  assign _102_ = mode;
  assign _008_ = _101_;
  assign _104_ = _088_;
  assign _106_ = mode;
  assign _007_ = _105_;
  assign _108_ = _086_;
  assign _110_ = _087_;
  assign _112_ = mode;
  assign _006_ = _111_;
  assign _114_ = _085_;
  assign _116_ = _087_;
  assign _118_ = mode;
  assign _005_ = _117_;
  assign _120_ = _087_;
  assign _122_ = mode;
  assign _004_ = _121_;
  assign _124_ = mode;
  assign _003_ = _123_;
  assign summand = _123_;
  assign _013_ = _125_;
  assign _014_ = _192_;
  assign _082_[0] = _014_[0];
  assign _015_[10] = _012_[10];
  assign _082_[9:1] = _193_;
  assign _012_[0] = _181_;
  assign _012_[1] = _182_;
  assign _028_ = _126_;
  assign _029_ = _013_[0];
  assign _012_[2] = _183_;
  assign _030_[0] = _127_;
  assign _031_[0] = _013_[0];
  assign _031_[1] = _014_[1];
  assign _030_[1] = _128_;
  assign _032_ = _013_[1];
  assign _012_[3] = _184_;
  assign _033_[0] = _129_;
  assign _034_[0] = _013_[0];
  assign _034_[1] = _014_[1];
  assign _034_[2] = _014_[2];
  assign _033_[1] = _130_;
  assign _035_[1] = _013_[1];
  assign _035_[2] = _014_[2];
  assign _033_[2] = _131_;
  assign _036_ = _013_[2];
  assign _012_[4] = _185_;
  assign _037_[0] = _132_;
  assign _038_[0] = _013_[0];
  assign _038_[1] = _014_[1];
  assign _038_[2] = _014_[2];
  assign _038_[3] = _014_[3];
  assign _037_[1] = _133_;
  assign _039_[1] = _013_[1];
  assign _039_[2] = _014_[2];
  assign _039_[3] = _014_[3];
  assign _037_[2] = _134_;
  assign _040_[2] = _013_[2];
  assign _040_[3] = _014_[3];
  assign _037_[3] = _135_;
  assign _041_ = _013_[3];
  assign _012_[5] = _186_;
  assign _042_[0] = _136_;
  assign _043_[0] = _013_[0];
  assign _043_[1] = _014_[1];
  assign _043_[2] = _014_[2];
  assign _043_[3] = _014_[3];
  assign _043_[4] = _014_[4];
  assign _042_[1] = _137_;
  assign _044_[1] = _013_[1];
  assign _044_[2] = _014_[2];
  assign _044_[3] = _014_[3];
  assign _044_[4] = _014_[4];
  assign _042_[2] = _138_;
  assign _045_[2] = _013_[2];
  assign _045_[3] = _014_[3];
  assign _045_[4] = _014_[4];
  assign _042_[3] = _139_;
  assign _046_[3] = _013_[3];
  assign _046_[4] = _014_[4];
  assign _042_[4] = _140_;
  assign _047_ = _013_[4];
  assign _012_[6] = _187_;
  assign _048_[0] = _141_;
  assign _049_[0] = _013_[0];
  assign _049_[1] = _014_[1];
  assign _049_[2] = _014_[2];
  assign _049_[3] = _014_[3];
  assign _049_[4] = _014_[4];
  assign _049_[5] = _014_[5];
  assign _048_[1] = _142_;
  assign _050_[1] = _013_[1];
  assign _050_[2] = _014_[2];
  assign _050_[3] = _014_[3];
  assign _050_[4] = _014_[4];
  assign _050_[5] = _014_[5];
  assign _048_[2] = _143_;
  assign _051_[2] = _013_[2];
  assign _051_[3] = _014_[3];
  assign _051_[4] = _014_[4];
  assign _051_[5] = _014_[5];
  assign _048_[3] = _144_;
  assign _052_[3] = _013_[3];
  assign _052_[4] = _014_[4];
  assign _052_[5] = _014_[5];
  assign _048_[4] = _145_;
  assign _053_[4] = _013_[4];
  assign _053_[5] = _014_[5];
  assign _048_[5] = _146_;
  assign _054_ = _013_[5];
  assign _012_[7] = _188_;
  assign _055_[0] = _147_;
  assign _056_[0] = _013_[0];
  assign _056_[1] = _014_[1];
  assign _056_[2] = _014_[2];
  assign _056_[3] = _014_[3];
  assign _056_[4] = _014_[4];
  assign _056_[5] = _014_[5];
  assign _056_[6] = _014_[6];
  assign _055_[1] = _148_;
  assign _057_[1] = _013_[1];
  assign _057_[2] = _014_[2];
  assign _057_[3] = _014_[3];
  assign _057_[4] = _014_[4];
  assign _057_[5] = _014_[5];
  assign _057_[6] = _014_[6];
  assign _055_[2] = _149_;
  assign _058_[2] = _013_[2];
  assign _058_[3] = _014_[3];
  assign _058_[4] = _014_[4];
  assign _058_[5] = _014_[5];
  assign _058_[6] = _014_[6];
  assign _055_[3] = _150_;
  assign _059_[3] = _013_[3];
  assign _059_[4] = _014_[4];
  assign _059_[5] = _014_[5];
  assign _059_[6] = _014_[6];
  assign _055_[4] = _151_;
  assign _060_[4] = _013_[4];
  assign _060_[5] = _014_[5];
  assign _060_[6] = _014_[6];
  assign _055_[5] = _152_;
  assign _061_[5] = _013_[5];
  assign _061_[6] = _014_[6];
  assign _055_[6] = _153_;
  assign _062_ = _013_[6];
  assign _012_[8] = _189_;
  assign _063_[0] = _154_;
  assign _064_[0] = _013_[0];
  assign _064_[1] = _014_[1];
  assign _064_[2] = _014_[2];
  assign _064_[3] = _014_[3];
  assign _064_[4] = _014_[4];
  assign _064_[5] = _014_[5];
  assign _064_[6] = _014_[6];
  assign _064_[7] = _014_[7];
  assign _063_[1] = _155_;
  assign _065_[1] = _013_[1];
  assign _065_[2] = _014_[2];
  assign _065_[3] = _014_[3];
  assign _065_[4] = _014_[4];
  assign _065_[5] = _014_[5];
  assign _065_[6] = _014_[6];
  assign _065_[7] = _014_[7];
  assign _063_[2] = _156_;
  assign _066_[2] = _013_[2];
  assign _066_[3] = _014_[3];
  assign _066_[4] = _014_[4];
  assign _066_[5] = _014_[5];
  assign _066_[6] = _014_[6];
  assign _066_[7] = _014_[7];
  assign _063_[3] = _157_;
  assign _067_[3] = _013_[3];
  assign _067_[4] = _014_[4];
  assign _067_[5] = _014_[5];
  assign _067_[6] = _014_[6];
  assign _067_[7] = _014_[7];
  assign _063_[4] = _158_;
  assign _068_[4] = _013_[4];
  assign _068_[5] = _014_[5];
  assign _068_[6] = _014_[6];
  assign _068_[7] = _014_[7];
  assign _063_[5] = _159_;
  assign _069_[5] = _013_[5];
  assign _069_[6] = _014_[6];
  assign _069_[7] = _014_[7];
  assign _063_[6] = _160_;
  assign _070_[6] = _013_[6];
  assign _070_[7] = _014_[7];
  assign _063_[7] = _161_;
  assign _071_ = _013_[7];
  assign _012_[9] = _190_;
  assign _072_[0] = _162_;
  assign _073_[0] = _013_[0];
  assign _073_[1] = _014_[1];
  assign _073_[2] = _014_[2];
  assign _073_[3] = _014_[3];
  assign _073_[4] = _014_[4];
  assign _073_[5] = _014_[5];
  assign _073_[6] = _014_[6];
  assign _073_[7] = _014_[7];
  assign _073_[8] = _014_[8];
  assign _072_[1] = _163_;
  assign _074_[1] = _013_[1];
  assign _074_[2] = _014_[2];
  assign _074_[3] = _014_[3];
  assign _074_[4] = _014_[4];
  assign _074_[5] = _014_[5];
  assign _074_[6] = _014_[6];
  assign _074_[7] = _014_[7];
  assign _074_[8] = _014_[8];
  assign _072_[2] = _164_;
  assign _075_[2] = _013_[2];
  assign _075_[3] = _014_[3];
  assign _075_[4] = _014_[4];
  assign _075_[5] = _014_[5];
  assign _075_[6] = _014_[6];
  assign _075_[7] = _014_[7];
  assign _075_[8] = _014_[8];
  assign _072_[3] = _165_;
  assign _076_[3] = _013_[3];
  assign _076_[4] = _014_[4];
  assign _076_[5] = _014_[5];
  assign _076_[6] = _014_[6];
  assign _076_[7] = _014_[7];
  assign _076_[8] = _014_[8];
  assign _072_[4] = _166_;
  assign _077_[4] = _013_[4];
  assign _077_[5] = _014_[5];
  assign _077_[6] = _014_[6];
  assign _077_[7] = _014_[7];
  assign _077_[8] = _014_[8];
  assign _072_[5] = _167_;
  assign _078_[5] = _013_[5];
  assign _078_[6] = _014_[6];
  assign _078_[7] = _014_[7];
  assign _078_[8] = _014_[8];
  assign _072_[6] = _168_;
  assign _079_[6] = _013_[6];
  assign _079_[7] = _014_[7];
  assign _079_[8] = _014_[8];
  assign _072_[7] = _169_;
  assign _080_[7] = _013_[7];
  assign _080_[8] = _014_[8];
  assign _072_[8] = _170_;
  assign _081_ = _013_[8];
  assign _012_[10] = _191_;
  assign _017_[0] = _171_;
  assign _018_[0] = _013_[0];
  assign _018_[1] = _014_[1];
  assign _018_[2] = _014_[2];
  assign _018_[3] = _014_[3];
  assign _018_[4] = _014_[4];
  assign _018_[5] = _014_[5];
  assign _018_[6] = _014_[6];
  assign _018_[7] = _014_[7];
  assign _018_[8] = _014_[8];
  assign _018_[9] = _014_[9];
  assign _017_[1] = _172_;
  assign _019_[1] = _013_[1];
  assign _019_[2] = _014_[2];
  assign _019_[3] = _014_[3];
  assign _019_[4] = _014_[4];
  assign _019_[5] = _014_[5];
  assign _019_[6] = _014_[6];
  assign _019_[7] = _014_[7];
  assign _019_[8] = _014_[8];
  assign _019_[9] = _014_[9];
  assign _017_[2] = _173_;
  assign _020_[2] = _013_[2];
  assign _020_[3] = _014_[3];
  assign _020_[4] = _014_[4];
  assign _020_[5] = _014_[5];
  assign _020_[6] = _014_[6];
  assign _020_[7] = _014_[7];
  assign _020_[8] = _014_[8];
  assign _020_[9] = _014_[9];
  assign _017_[3] = _174_;
  assign _021_[3] = _013_[3];
  assign _021_[4] = _014_[4];
  assign _021_[5] = _014_[5];
  assign _021_[6] = _014_[6];
  assign _021_[7] = _014_[7];
  assign _021_[8] = _014_[8];
  assign _021_[9] = _014_[9];
  assign _017_[4] = _175_;
  assign _022_[4] = _013_[4];
  assign _022_[5] = _014_[5];
  assign _022_[6] = _014_[6];
  assign _022_[7] = _014_[7];
  assign _022_[8] = _014_[8];
  assign _022_[9] = _014_[9];
  assign _017_[5] = _176_;
  assign _023_[5] = _013_[5];
  assign _023_[6] = _014_[6];
  assign _023_[7] = _014_[7];
  assign _023_[8] = _014_[8];
  assign _023_[9] = _014_[9];
  assign _017_[6] = _177_;
  assign _024_[6] = _013_[6];
  assign _024_[7] = _014_[7];
  assign _024_[8] = _014_[8];
  assign _024_[9] = _014_[9];
  assign _017_[7] = _178_;
  assign _025_[7] = _013_[7];
  assign _025_[8] = _014_[8];
  assign _025_[9] = _014_[9];
  assign _017_[8] = _179_;
  assign _026_[8] = _013_[8];
  assign _026_[9] = _014_[9];
  assign _017_[9] = _180_;
  assign _027_ = _013_[9];
endmodule
