/* Generated by Yosys 0.45 (git sha1 9ed031ddd, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* cells_not_processed =  1  *)
(* src = "counter.v:1.1-39.10" *)
module counter(clk, rst, mode, cnt);
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _000_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _001_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _002_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _003_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _004_;
  (* src = "counter.v:10.5-30.8" *)
  wire [9:0] _005_;
  (* src = "counter.v:36.20-36.33|map.v:15.22-15.23" *)
  (* unused_bits = "10" *)
  wire [10:0] _006_;
  (* src = "counter.v:36.20-36.33|map.v:13.22-13.23" *)
  (* unused_bits = "9" *)
  wire [10:0] _007_;
  (* src = "counter.v:36.20-36.33|map.v:14.22-14.23" *)
  wire [10:0] _008_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [1:0] _009_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [2:0] _010_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [3:0] _011_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [4:0] _012_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [5:0] _013_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [6:0] _014_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [7:0] _015_;
  (* src = "counter.v:36.20-36.33|map.v:25.26-25.37" *)
  wire [8:0] _016_;
  (* src = "counter.v:36.20-36.33" *)
  wire [9:0] _017_;
  wire [4:0] _018_;
  wire [1:0] _019_;
  wire _020_;
  wire [4:0] _021_;
  wire [1:0] _022_;
  wire _023_;
  wire _024_;
  wire [1:0] _025_;
  wire [1:0] _026_;
  wire _027_;
  wire [2:0] _028_;
  wire _029_;
  wire [2:0] _030_;
  wire [1:0] _031_;
  wire [3:0] _032_;
  wire [1:0] _033_;
  wire [3:0] _034_;
  wire [1:0] _035_;
  wire _036_;
  wire [1:0] _037_;
  wire [2:0] _038_;
  wire [1:0] _039_;
  wire [3:0] _040_;
  wire [1:0] _041_;
  wire [1:0] _042_;
  wire [2:0] _043_;
  wire [1:0] _044_;
  wire [2:0] _045_;
  wire [1:0] _046_;
  wire [1:0] _047_;
  wire [2:0] _048_;
  wire _049_;
  wire [1:0] _050_;
  wire [1:0] _051_;
  wire _052_;
  wire [1:0] _053_;
  wire _054_;
  wire [4:0] _055_;
  wire [1:0] _056_;
  wire _057_;
  wire [4:0] _058_;
  wire [1:0] _059_;
  wire _060_;
  wire [4:0] _061_;
  wire [1:0] _062_;
  wire _063_;
  wire [4:0] _064_;
  wire [1:0] _065_;
  wire _066_;
  (* src = "counter.v:13.17-13.32" *)
  wire _067_;
  (* src = "counter.v:22.17-22.31" *)
  wire _068_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.21-279.23" *)
  wire [9:0] _069_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "4 5 6" *)
  wire [9:0] _070_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "3 4 5 6 7 8" *)
  wire [9:0] _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 4 5 6" *)
  wire [9:0] _075_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "1 2 3 4 5 6 7 8" *)
  wire [9:0] _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 4 5 6" *)
  wire [9:0] _080_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "1 2 3 4 5 6 7 8" *)
  wire [9:0] _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 4 5 6" *)
  wire [9:0] _087_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "2 3 4 5 6 7 8" *)
  wire [9:0] _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _094_;
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _095_;
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _096_;
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _097_;
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _098_;
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _099_;
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _100_;
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _101_;
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _102_;
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _103_;
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _104_;
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _105_;
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _106_;
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _107_;
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _108_;
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _109_;
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _110_;
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _111_;
  (* src = "counter.v:3.17-3.20" *)
  input clk;
  wire clk;
  (* init = 10'h3ce *)
  (* src = "counter.v:6.29-6.32" *)
  output [9:0] cnt;
  wire [9:0] cnt;
  (* src = "counter.v:5.17-5.21" *)
  input mode;
  wire mode;
  (* src = "counter.v:4.17-4.20" *)
  input rst;
  wire rst;
  (* src = "counter.v:8.22-8.29" *)
  wire [9:0] summand;
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP0_  \cnt_reg[0]  /* _112_ */ (
    .C(clk),
    .D(_008_[0]),
    .Q(cnt[0]),
    .R(rst)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP1_  \cnt_reg[1]  /* _113_ */ (
    .C(clk),
    .D(_017_[1]),
    .Q(cnt[1]),
    .R(rst)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP1_  \cnt_reg[2]  /* _114_ */ (
    .C(clk),
    .D(_017_[2]),
    .Q(cnt[2]),
    .R(rst)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP1_  \cnt_reg[3]  /* _115_ */ (
    .C(clk),
    .D(_017_[3]),
    .Q(cnt[3]),
    .R(rst)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP0_  \cnt_reg[4]  /* _116_ */ (
    .C(clk),
    .D(_017_[4]),
    .Q(cnt[4]),
    .R(rst)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP0_  \cnt_reg[5]  /* _117_ */ (
    .C(clk),
    .D(_017_[5]),
    .Q(cnt[5]),
    .R(rst)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP1_  \cnt_reg[6]  /* _118_ */ (
    .C(clk),
    .D(_017_[6]),
    .Q(cnt[6]),
    .R(rst)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP1_  \cnt_reg[7]  /* _119_ */ (
    .C(clk),
    .D(_017_[7]),
    .Q(cnt[7]),
    .R(rst)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP1_  \cnt_reg[8]  /* _120_ */ (
    .C(clk),
    .D(_017_[8]),
    .Q(cnt[8]),
    .R(rst)
  );
  (* src = "counter.v:32.5-38.8" *)
  \$_SDFF_PP1_  \cnt_reg[9]  /* _121_ */ (
    .C(clk),
    .D(_017_[9]),
    .Q(cnt[9]),
    .R(rst)
  );
  \$_NOT_  _122_ (
    .A(cnt[0]),
    .Y(_069_[0])
  );
  (* src = "counter.v:13.17-13.32" *)
  \$_OR_  _123_ (
    .A(cnt[0]),
    .B(cnt[1]),
    .Y(_018_[0])
  );
  (* src = "counter.v:13.17-13.32" *)
  \$_OR_  _124_ (
    .A(cnt[2]),
    .B(cnt[3]),
    .Y(_018_[1])
  );
  (* src = "counter.v:13.17-13.32" *)
  \$_OR_  _125_ (
    .A(_018_[0]),
    .B(_018_[1]),
    .Y(_019_[0])
  );
  (* src = "counter.v:13.17-13.32" *)
  \$_OR_  _126_ (
    .A(_019_[0]),
    .B(_019_[1]),
    .Y(_020_)
  );
  (* src = "counter.v:13.17-13.32" *)
  \$_OR_  _127_ (
    .A(_020_),
    .B(_018_[4]),
    .Y(_067_)
  );
  (* src = "counter.v:22.17-22.31" *)
  \$_OR_  _128_ (
    .A(cnt[0]),
    .B(_069_[1]),
    .Y(_021_[0])
  );
  (* src = "counter.v:22.17-22.31" *)
  \$_OR_  _129_ (
    .A(_069_[2]),
    .B(_069_[3]),
    .Y(_021_[1])
  );
  (* src = "counter.v:22.17-22.31" *)
  \$_OR_  _130_ (
    .A(_069_[4]),
    .B(_069_[5]),
    .Y(_018_[2])
  );
  (* src = "counter.v:22.17-22.31" *)
  \$_OR_  _131_ (
    .A(_069_[6]),
    .B(_069_[7]),
    .Y(_018_[3])
  );
  (* src = "counter.v:22.17-22.31" *)
  \$_OR_  _132_ (
    .A(_069_[8]),
    .B(_069_[9]),
    .Y(_018_[4])
  );
  (* src = "counter.v:22.17-22.31" *)
  \$_OR_  _133_ (
    .A(_021_[0]),
    .B(_021_[1]),
    .Y(_022_[0])
  );
  (* src = "counter.v:22.17-22.31" *)
  \$_OR_  _134_ (
    .A(_018_[2]),
    .B(_018_[3]),
    .Y(_019_[1])
  );
  (* src = "counter.v:22.17-22.31" *)
  \$_OR_  _135_ (
    .A(_022_[0]),
    .B(_019_[1]),
    .Y(_023_)
  );
  (* src = "counter.v:22.17-22.31" *)
  \$_OR_  _136_ (
    .A(_023_),
    .B(_018_[4]),
    .Y(_068_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _137_ (
    .A(_008_[8]),
    .B(_007_[7]),
    .Y(_016_[7])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _138_ (
    .A(_024_),
    .B(_007_[6]),
    .Y(_016_[6])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _139_ (
    .A(_008_[8]),
    .B(_007_[5]),
    .Y(_025_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _140_ (
    .A(_025_[0]),
    .B(_025_[1]),
    .Y(_016_[5])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _141_ (
    .A(_026_[0]),
    .B(_024_),
    .Y(_027_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _142_ (
    .A(_027_),
    .B(_007_[4]),
    .Y(_016_[4])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _143_ (
    .A(_008_[8]),
    .B(_007_[3]),
    .Y(_028_[2])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _144_ (
    .A(_029_),
    .B(_028_[2]),
    .Y(_016_[3])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _145_ (
    .A(_008_[7]),
    .B(_008_[8]),
    .Y(_024_)
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _146_ (
    .A(_024_),
    .B(_007_[2]),
    .Y(_031_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _147_ (
    .A(_031_[0]),
    .B(_031_[1]),
    .Y(_016_[2])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _148_ (
    .A(_008_[8]),
    .B(_007_[1]),
    .Y(_032_[3])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _149_ (
    .A(_025_[0]),
    .B(_032_[3]),
    .Y(_033_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _150_ (
    .A(_033_[0]),
    .B(_033_[1]),
    .Y(_016_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _151_ (
    .A(_011_[0]),
    .B(_029_),
    .Y(_015_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _152_ (
    .A(_015_[0]),
    .B(_008_[8]),
    .Y(_016_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _153_ (
    .A(_016_[0]),
    .B(_016_[1]),
    .Y(_034_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _154_ (
    .A(_016_[2]),
    .B(_016_[3]),
    .Y(_034_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _155_ (
    .A(_016_[4]),
    .B(_016_[5]),
    .Y(_034_[2])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _156_ (
    .A(_016_[6]),
    .B(_016_[7]),
    .Y(_034_[3])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _157_ (
    .A(_034_[0]),
    .B(_034_[1]),
    .Y(_035_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _158_ (
    .A(_034_[2]),
    .B(_034_[3]),
    .Y(_035_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _159_ (
    .A(_035_[0]),
    .B(_035_[1]),
    .Y(_036_)
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _160_ (
    .A(_036_),
    .B(_007_[8]),
    .Y(_006_[9])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _161_ (
    .A(_008_[7]),
    .B(_007_[6]),
    .Y(_015_[6])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _162_ (
    .A(_025_[0]),
    .B(_007_[5]),
    .Y(_015_[5])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _163_ (
    .A(_008_[7]),
    .B(_007_[4]),
    .Y(_037_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _164_ (
    .A(_026_[0]),
    .B(_037_[1]),
    .Y(_015_[4])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _165_ (
    .A(_029_),
    .B(_007_[3]),
    .Y(_015_[3])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _166_ (
    .A(_008_[7]),
    .B(_007_[2]),
    .Y(_038_[2])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _167_ (
    .A(_031_[0]),
    .B(_038_[2]),
    .Y(_015_[2])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _168_ (
    .A(_025_[0]),
    .B(_007_[1]),
    .Y(_039_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _169_ (
    .A(_033_[0]),
    .B(_039_[1]),
    .Y(_015_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _170_ (
    .A(_008_[6]),
    .B(_008_[7]),
    .Y(_025_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _171_ (
    .A(_028_[0]),
    .B(_025_[0]),
    .Y(_029_)
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _172_ (
    .A(_015_[0]),
    .B(_015_[1]),
    .Y(_040_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _173_ (
    .A(_015_[2]),
    .B(_015_[3]),
    .Y(_040_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _174_ (
    .A(_015_[4]),
    .B(_015_[5]),
    .Y(_040_[2])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _175_ (
    .A(_015_[6]),
    .B(_007_[7]),
    .Y(_040_[3])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _176_ (
    .A(_040_[0]),
    .B(_040_[1]),
    .Y(_041_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _177_ (
    .A(_040_[2]),
    .B(_040_[3]),
    .Y(_041_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _178_ (
    .A(_041_[0]),
    .B(_041_[1]),
    .Y(_006_[8])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _179_ (
    .A(_008_[6]),
    .B(_007_[5]),
    .Y(_014_[5])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _180_ (
    .A(_026_[0]),
    .B(_007_[4]),
    .Y(_014_[4])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _181_ (
    .A(_008_[6]),
    .B(_007_[3]),
    .Y(_042_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _182_ (
    .A(_028_[0]),
    .B(_042_[1]),
    .Y(_014_[3])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _183_ (
    .A(_008_[5]),
    .B(_008_[6]),
    .Y(_026_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _184_ (
    .A(_030_[0]),
    .B(_026_[0]),
    .Y(_031_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _185_ (
    .A(_031_[0]),
    .B(_007_[2]),
    .Y(_014_[2])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _186_ (
    .A(_008_[6]),
    .B(_007_[1]),
    .Y(_043_[2])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _187_ (
    .A(_033_[0]),
    .B(_043_[2]),
    .Y(_014_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _188_ (
    .A(_028_[0]),
    .B(_008_[6]),
    .Y(_044_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _189_ (
    .A(_011_[0]),
    .B(_044_[1]),
    .Y(_014_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _190_ (
    .A(_014_[0]),
    .B(_014_[1]),
    .Y(_045_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _191_ (
    .A(_014_[2]),
    .B(_014_[3]),
    .Y(_045_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _192_ (
    .A(_014_[4]),
    .B(_014_[5]),
    .Y(_045_[2])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _193_ (
    .A(_045_[0]),
    .B(_045_[1]),
    .Y(_046_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _194_ (
    .A(_045_[2]),
    .B(_007_[6]),
    .Y(_046_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _195_ (
    .A(_046_[0]),
    .B(_046_[1]),
    .Y(_006_[7])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _196_ (
    .A(_008_[5]),
    .B(_007_[4]),
    .Y(_013_[4])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _197_ (
    .A(_028_[0]),
    .B(_007_[3]),
    .Y(_013_[3])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _198_ (
    .A(_008_[5]),
    .B(_007_[2]),
    .Y(_047_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _199_ (
    .A(_030_[0]),
    .B(_047_[1]),
    .Y(_013_[2])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _200_ (
    .A(_032_[0]),
    .B(_028_[0]),
    .Y(_033_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _201_ (
    .A(_033_[0]),
    .B(_007_[1]),
    .Y(_013_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _202_ (
    .A(_008_[4]),
    .B(_008_[5]),
    .Y(_028_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _203_ (
    .A(_011_[0]),
    .B(_028_[0]),
    .Y(_013_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _204_ (
    .A(_013_[0]),
    .B(_013_[1]),
    .Y(_048_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _205_ (
    .A(_013_[2]),
    .B(_013_[3]),
    .Y(_048_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _206_ (
    .A(_013_[4]),
    .B(_007_[5]),
    .Y(_048_[2])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _207_ (
    .A(_048_[0]),
    .B(_048_[1]),
    .Y(_049_)
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _208_ (
    .A(_049_),
    .B(_048_[2]),
    .Y(_006_[6])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _209_ (
    .A(_008_[4]),
    .B(_007_[3]),
    .Y(_012_[3])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _210_ (
    .A(_008_[3]),
    .B(_008_[4]),
    .Y(_030_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _211_ (
    .A(_030_[0]),
    .B(_007_[2]),
    .Y(_012_[2])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _212_ (
    .A(_008_[4]),
    .B(_007_[1]),
    .Y(_050_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _213_ (
    .A(_032_[0]),
    .B(_050_[1]),
    .Y(_012_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _214_ (
    .A(_009_[0]),
    .B(_032_[0]),
    .Y(_011_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _215_ (
    .A(_011_[0]),
    .B(_008_[4]),
    .Y(_012_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _216_ (
    .A(_012_[0]),
    .B(_012_[1]),
    .Y(_051_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _217_ (
    .A(_012_[2]),
    .B(_012_[3]),
    .Y(_051_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _218_ (
    .A(_051_[0]),
    .B(_051_[1]),
    .Y(_052_)
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _219_ (
    .A(_052_),
    .B(_007_[4]),
    .Y(_006_[5])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _220_ (
    .A(_008_[3]),
    .B(_007_[2]),
    .Y(_011_[2])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _221_ (
    .A(_032_[0]),
    .B(_007_[1]),
    .Y(_011_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _222_ (
    .A(_008_[2]),
    .B(_008_[3]),
    .Y(_032_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _223_ (
    .A(_011_[0]),
    .B(_011_[1]),
    .Y(_053_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _224_ (
    .A(_011_[2]),
    .B(_007_[3]),
    .Y(_053_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _225_ (
    .A(_053_[0]),
    .B(_053_[1]),
    .Y(_006_[4])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _226_ (
    .A(_008_[2]),
    .B(_007_[1]),
    .Y(_010_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _227_ (
    .A(_006_[1]),
    .B(_008_[1]),
    .Y(_009_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:30.41-30.50" *)
  \$_AND_  _228_ (
    .A(_009_[0]),
    .B(_008_[2]),
    .Y(_010_[0])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _229_ (
    .A(_010_[0]),
    .B(_010_[1]),
    .Y(_054_)
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _230_ (
    .A(_054_),
    .B(_007_[2]),
    .Y(_006_[3])
  );
  (* src = "counter.v:36.20-36.33|map.v:26.27-26.39" *)
  \$_OR_  _231_ (
    .A(_009_[0]),
    .B(_007_[1]),
    .Y(_006_[2])
  );
  (* src = {0{1'b0}} *)
  \$_OR_  _232_ (
    .A(_079_),
    .B(_077_),
    .Y(_005_[9])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37" *)
  \$_AND_  _233_ (
    .A(_075_[1]),
    .B(_055_[1]),
    .Y(_056_[0])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37" *)
  \$_AND_  _234_ (
    .A(_056_[0]),
    .B(_056_[1]),
    .Y(_057_)
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37" *)
  \$_AND_  _235_ (
    .A(_057_),
    .B(_055_[4]),
    .Y(_077_)
  );
  (* src = {0{1'b0}} *)
  \$_OR_  _236_ (
    .A(_074_),
    .B(_072_),
    .Y(_004_[9])
  );
  (* src = "counter.v:23.21-23.37" *)
  \$_AND_  _237_ (
    .A(cnt[0]),
    .B(cnt[1]),
    .Y(_058_[0])
  );
  (* src = "counter.v:23.21-23.37" *)
  \$_AND_  _238_ (
    .A(_058_[0]),
    .B(_070_[3]),
    .Y(_059_[0])
  );
  (* src = "counter.v:23.21-23.37" *)
  \$_AND_  _239_ (
    .A(_055_[2]),
    .B(_055_[3]),
    .Y(_056_[1])
  );
  (* src = "counter.v:23.21-23.37" *)
  \$_AND_  _240_ (
    .A(_059_[0]),
    .B(_056_[1]),
    .Y(_060_)
  );
  (* src = "counter.v:23.21-23.37" *)
  \$_AND_  _241_ (
    .A(_060_),
    .B(_055_[4]),
    .Y(_072_)
  );
  (* src = {0{1'b0}} *)
  \$_OR_  _242_ (
    .A(_089_),
    .B(_090_),
    .Y(_002_[3])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36" *)
  \$_AND_  _243_ (
    .A(cnt[0]),
    .B(_069_[1]),
    .Y(_061_[0])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36" *)
  \$_AND_  _244_ (
    .A(_061_[0]),
    .B(_070_[3]),
    .Y(_062_[0])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36" *)
  \$_AND_  _245_ (
    .A(_062_[0]),
    .B(_062_[1]),
    .Y(_063_)
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36" *)
  \$_AND_  _246_ (
    .A(_063_),
    .B(_061_[4]),
    .Y(_090_)
  );
  (* src = {0{1'b0}} *)
  \$_OR_  _247_ (
    .A(_082_),
    .B(_083_),
    .Y(_001_[2])
  );
  (* src = "counter.v:14.21-14.36" *)
  \$_AND_  _248_ (
    .A(_064_[0]),
    .B(_064_[1]),
    .Y(_065_[0])
  );
  (* src = "counter.v:14.21-14.36" *)
  \$_AND_  _249_ (
    .A(_065_[0]),
    .B(_062_[1]),
    .Y(_066_)
  );
  (* src = "counter.v:14.21-14.36" *)
  \$_AND_  _250_ (
    .A(_066_),
    .B(_061_[4]),
    .Y(_083_)
  );
  (* src = "counter.v:22.17-22.31|counter.v:22.13-28.16" *)
  \$_AND_  _251_ (
    .A(_068_),
    .B(_004_[9]),
    .Y(_003_[4])
  );
  (* src = "counter.v:22.17-22.31|counter.v:22.13-28.16" *)
  \$_MUX_  _252_ (
    .A(_005_[9]),
    .B(_004_[9]),
    .S(_068_),
    .Y(_003_[9])
  );
  (* src = "counter.v:22.17-22.31|counter.v:22.13-28.16" *)
  \$_MUX_  _253_ (
    .A(_005_[9]),
    .B(1'h0),
    .S(_068_),
    .Y(_003_[3])
  );
  (* src = "counter.v:13.17-13.32|counter.v:13.13-19.16" *)
  \$_AND_  _254_ (
    .A(_067_),
    .B(_001_[2]),
    .Y(_000_[2])
  );
  (* src = "counter.v:13.17-13.32|counter.v:13.13-19.16" *)
  \$_MUX_  _255_ (
    .A(_002_[3]),
    .B(1'h0),
    .S(_067_),
    .Y(_000_[3])
  );
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$_MUX_  _256_ (
    .A(_003_[4]),
    .B(_000_[2]),
    .S(mode),
    .Y(summand[0])
  );
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$_MUX_  _257_ (
    .A(_003_[9]),
    .B(_000_[3]),
    .S(mode),
    .Y(summand[1])
  );
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$_MUX_  _258_ (
    .A(_003_[9]),
    .B(_000_[2]),
    .S(mode),
    .Y(summand[2])
  );
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$_MUX_  _259_ (
    .A(_003_[3]),
    .B(_000_[3]),
    .S(mode),
    .Y(summand[3])
  );
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$_MUX_  _260_ (
    .A(_003_[4]),
    .B(1'h0),
    .S(mode),
    .Y(summand[4])
  );
  (* src = "counter.v:12.13-12.17|counter.v:12.9-29.12" *)
  \$_MUX_  _261_ (
    .A(_003_[9]),
    .B(1'h0),
    .S(mode),
    .Y(summand[9])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36" *)
  \$_NOT_  _262_ (
    .A(_091_),
    .Y(_089_)
  );
  (* src = "counter.v:14.21-14.36" *)
  \$_NOT_  _263_ (
    .A(_084_),
    .Y(_082_)
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _264_ (
    .A(cnt[4]),
    .Y(_069_[4])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _265_ (
    .A(cnt[1]),
    .Y(_069_[1])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _266_ (
    .A(cnt[2]),
    .Y(_069_[2])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _267_ (
    .A(cnt[3]),
    .Y(_069_[3])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _268_ (
    .A(cnt[9]),
    .Y(_069_[9])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _269_ (
    .A(cnt[5]),
    .Y(_069_[5])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _270_ (
    .A(cnt[6]),
    .Y(_069_[6])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _271_ (
    .A(cnt[7]),
    .Y(_069_[7])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *)
  \$_NOT_  _272_ (
    .A(cnt[8]),
    .Y(_069_[8])
  );
  (* src = {0{1'b0}} *)
  \$_AND_  _273_ (
    .A(cnt[0]),
    .B(summand[0]),
    .Y(_006_[1])
  );
  (* src = {0{1'b0}} *)
  \$_AND_  _274_ (
    .A(cnt[1]),
    .B(summand[1]),
    .Y(_007_[1])
  );
  (* src = {0{1'b0}} *)
  \$_AND_  _275_ (
    .A(cnt[2]),
    .B(summand[2]),
    .Y(_007_[2])
  );
  (* src = {0{1'b0}} *)
  \$_AND_  _276_ (
    .A(cnt[3]),
    .B(summand[3]),
    .Y(_007_[3])
  );
  (* src = {0{1'b0}} *)
  \$_AND_  _277_ (
    .A(cnt[4]),
    .B(summand[4]),
    .Y(_007_[4])
  );
  (* src = {0{1'b0}} *)
  \$_AND_  _278_ (
    .A(cnt[5]),
    .B(summand[9]),
    .Y(_007_[5])
  );
  (* src = {0{1'b0}} *)
  \$_AND_  _279_ (
    .A(cnt[6]),
    .B(summand[9]),
    .Y(_007_[6])
  );
  (* src = {0{1'b0}} *)
  \$_AND_  _280_ (
    .A(cnt[7]),
    .B(summand[9]),
    .Y(_007_[7])
  );
  (* src = {0{1'b0}} *)
  \$_AND_  _281_ (
    .A(cnt[8]),
    .B(summand[9]),
    .Y(_007_[8])
  );
  (* src = "counter.v:36.20-36.33|map.v:44.29-44.60" *)
  \$_XOR_  _282_ (
    .A(_008_[1]),
    .B(_006_[1]),
    .Y(_017_[1])
  );
  (* src = "counter.v:36.20-36.33|map.v:44.29-44.60" *)
  \$_XOR_  _283_ (
    .A(_008_[2]),
    .B(_006_[2]),
    .Y(_017_[2])
  );
  (* src = "counter.v:36.20-36.33|map.v:44.29-44.60" *)
  \$_XOR_  _284_ (
    .A(_008_[3]),
    .B(_006_[3]),
    .Y(_017_[3])
  );
  (* src = "counter.v:36.20-36.33|map.v:44.29-44.60" *)
  \$_XOR_  _285_ (
    .A(_008_[4]),
    .B(_006_[4]),
    .Y(_017_[4])
  );
  (* src = "counter.v:36.20-36.33|map.v:44.29-44.60" *)
  \$_XOR_  _286_ (
    .A(_008_[5]),
    .B(_006_[5]),
    .Y(_017_[5])
  );
  (* src = "counter.v:36.20-36.33|map.v:44.29-44.60" *)
  \$_XOR_  _287_ (
    .A(_008_[6]),
    .B(_006_[6]),
    .Y(_017_[6])
  );
  (* src = "counter.v:36.20-36.33|map.v:44.29-44.60" *)
  \$_XOR_  _288_ (
    .A(_008_[7]),
    .B(_006_[7]),
    .Y(_017_[7])
  );
  (* src = "counter.v:36.20-36.33|map.v:44.29-44.60" *)
  \$_XOR_  _289_ (
    .A(_008_[8]),
    .B(_006_[8]),
    .Y(_017_[8])
  );
  (* src = "counter.v:36.20-36.33|map.v:44.29-44.60" *)
  \$_XOR_  _290_ (
    .A(_008_[9]),
    .B(_006_[9]),
    .Y(_017_[9])
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _291_ (
    .A(cnt[0]),
    .B(summand[0]),
    .Y(_008_[0])
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _292_ (
    .A(cnt[1]),
    .B(summand[1]),
    .Y(_008_[1])
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _293_ (
    .A(cnt[2]),
    .B(summand[2]),
    .Y(_008_[2])
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _294_ (
    .A(cnt[3]),
    .B(summand[3]),
    .Y(_008_[3])
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _295_ (
    .A(cnt[4]),
    .B(summand[4]),
    .Y(_008_[4])
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _296_ (
    .A(cnt[5]),
    .B(summand[9]),
    .Y(_008_[5])
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _297_ (
    .A(cnt[6]),
    .B(summand[9]),
    .Y(_008_[6])
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _298_ (
    .A(cnt[7]),
    .B(summand[9]),
    .Y(_008_[7])
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _299_ (
    .A(cnt[8]),
    .B(summand[9]),
    .Y(_008_[8])
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _300_ (
    .A(cnt[9]),
    .B(summand[9]),
    .Y(_008_[9])
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _301_ (
    .A(_075_[9]),
    .B(_075_[8]),
    .Y(_078_)
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _302_ (
    .A(_078_),
    .B(_076_[9]),
    .Y(_079_)
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _303_ (
    .A(_070_[9]),
    .B(_070_[8]),
    .Y(_073_)
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _304_ (
    .A(_073_),
    .B(_071_[9]),
    .Y(_074_)
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _305_ (
    .A(_087_[9]),
    .B(_087_[8]),
    .Y(_092_)
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _306_ (
    .A(_092_),
    .B(_088_[9]),
    .Y(_093_)
  );
  (* src = {0{1'b0}} *)
  \$_OR_  _307_ (
    .A(_093_),
    .B(_090_),
    .Y(_091_)
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _308_ (
    .A(_080_[9]),
    .B(_080_[8]),
    .Y(_085_)
  );
  (* src = {0{1'b0}} *)
  \$_XOR_  _309_ (
    .A(_085_),
    .B(_081_[9]),
    .Y(_086_)
  );
  (* src = {0{1'b0}} *)
  \$_OR_  _310_ (
    .A(_086_),
    .B(_083_),
    .Y(_084_)
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _311_ (
    .A(cnt[9]),
    .B(_075_[8]),
    .Y(_076_[9])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _312_ (
    .A(cnt[9]),
    .B(_070_[8]),
    .Y(_071_[9])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _313_ (
    .A(_069_[9]),
    .B(_087_[8]),
    .Y(_088_[9])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _314_ (
    .A(_069_[9]),
    .B(_080_[8]),
    .Y(_081_[9])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _315_ (
    .A(_069_[8]),
    .B(_080_[7]),
    .Y(_080_[8])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _316_ (
    .A(_069_[1]),
    .B(_069_[0]),
    .Y(_075_[1])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _317_ (
    .A(cnt[3]),
    .B(_069_[2]),
    .Y(_100_)
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _318_ (
    .A(_056_[1]),
    .B(_075_[3]),
    .Y(_101_)
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _319_ (
    .A(cnt[3]),
    .B(cnt[2]),
    .Y(_055_[1])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _320_ (
    .A(_055_[4]),
    .B(_075_[7]),
    .Y(_102_)
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _321_ (
    .A(cnt[8]),
    .B(_075_[7]),
    .Y(_103_)
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _322_ (
    .A(_069_[3]),
    .B(_100_),
    .Y(_104_)
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _323_ (
    .A(_069_[9]),
    .B(_094_),
    .Y(_099_)
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _324_ (
    .A(_104_),
    .B(_056_[0]),
    .Y(_075_[3])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _325_ (
    .A(_095_),
    .B(_101_),
    .Y(_075_[7])
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.12-248.41" *)
  \$_OR_  _326_ (
    .A(_099_),
    .B(_102_),
    .Y(_075_[9])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _327_ (
    .A(_069_[1]),
    .B(_064_[0]),
    .Y(_080_[1])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _328_ (
    .A(_062_[1]),
    .B(_080_[3]),
    .Y(_108_)
  );
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.12-248.41" *)
  \$_OR_  _329_ (
    .A(_069_[8]),
    .B(_103_),
    .Y(_075_[8])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _330_ (
    .A(_070_[3]),
    .B(_069_[1]),
    .Y(_087_[3])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _331_ (
    .A(_061_[3]),
    .B(_069_[5]),
    .Y(_107_)
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _332_ (
    .A(_064_[1]),
    .B(_080_[1]),
    .Y(_106_)
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _333_ (
    .A(cnt[9]),
    .B(cnt[8]),
    .Y(_055_[4])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _334_ (
    .A(_069_[7]),
    .B(_105_),
    .Y(_109_)
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _335_ (
    .A(cnt[7]),
    .B(_069_[6]),
    .Y(_105_)
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _336_ (
    .A(_070_[3]),
    .B(_106_),
    .Y(_080_[3])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _337_ (
    .A(_110_),
    .B(_108_),
    .Y(_080_[7])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _338_ (
    .A(_062_[1]),
    .B(_087_[3]),
    .Y(_111_)
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _339_ (
    .A(_061_[4]),
    .B(_087_[7]),
    .Y(_087_[9])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _340_ (
    .A(cnt[9]),
    .B(_069_[8]),
    .Y(_094_)
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _341_ (
    .A(_055_[3]),
    .B(_069_[5]),
    .Y(_095_)
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _342_ (
    .A(_056_[1]),
    .B(_070_[3]),
    .Y(_096_)
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _343_ (
    .A(_069_[7]),
    .B(_069_[6]),
    .Y(_055_[3])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _344_ (
    .A(_061_[4]),
    .B(_080_[7]),
    .Y(_080_[9])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _345_ (
    .A(cnt[5]),
    .B(_069_[4]),
    .Y(_055_[2])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _346_ (
    .A(_069_[8]),
    .B(_087_[7]),
    .Y(_087_[8])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _347_ (
    .A(_069_[3]),
    .B(cnt[2]),
    .Y(_064_[1])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _348_ (
    .A(_061_[3]),
    .B(_055_[2]),
    .Y(_062_[1])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _349_ (
    .A(_069_[9]),
    .B(_069_[8]),
    .Y(_061_[4])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)
  \$_AND_  _350_ (
    .A(cnt[7]),
    .B(cnt[6]),
    .Y(_061_[3])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _351_ (
    .A(_055_[4]),
    .B(_070_[7]),
    .Y(_097_)
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _352_ (
    .A(cnt[8]),
    .B(_070_[7]),
    .Y(_098_)
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _353_ (
    .A(_095_),
    .B(_096_),
    .Y(_070_[7])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.12-248.41" *)
  \$_OR_  _354_ (
    .A(_099_),
    .B(_097_),
    .Y(_070_[9])
  );
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.12-248.41" *)
  \$_OR_  _355_ (
    .A(_069_[8]),
    .B(_098_),
    .Y(_070_[8])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _356_ (
    .A(_069_[3]),
    .B(_069_[2]),
    .Y(_070_[3])
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _357_ (
    .A(_109_),
    .B(_107_),
    .Y(_110_)
  );
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  \$_OR_  _358_ (
    .A(_110_),
    .B(_111_),
    .Y(_087_[7])
  );
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _359_ (
    .A(cnt[1]),
    .B(_069_[0]),
    .Y(_064_[0])
  );
  assign { _000_[9:4], _000_[1:0] } = { 6'h00, _000_[3:2] };
  assign { _001_[9:3], _001_[1:0] } = { 8'h00, _001_[2] };
  assign { _002_[9:4], _002_[2:0] } = { 7'h00, _002_[3], 1'h0 };
  assign { _003_[8:5], _003_[2:0] } = { _003_[9], _003_[9], _003_[9], _003_[9], _003_[9], _003_[9], _003_[4] };
  assign _004_[8:0] = { _004_[9], _004_[9], _004_[9], _004_[9], _004_[9], 1'h0, _004_[9], _004_[9], _004_[9] };
  assign _005_[8:0] = { _005_[9], _005_[9], _005_[9], _005_[9], 1'h0, _005_[9], _005_[9], _005_[9], 1'h0 };
  assign _006_[0] = 1'hx;
  assign { _007_[10], _007_[0] } = { 1'h0, _006_[1] };
  assign _008_[10] = 1'h0;
  assign _009_[1] = _007_[1];
  assign _010_[2] = _007_[2];
  assign _011_[3] = _007_[3];
  assign _012_[4] = _007_[4];
  assign _013_[5] = _007_[5];
  assign _014_[6] = _007_[6];
  assign _015_[7] = _007_[7];
  assign _016_[8] = _007_[8];
  assign _017_[0] = _008_[0];
  assign _021_[4:2] = _018_[4:2];
  assign _022_[1] = _019_[1];
  assign _026_[1] = _024_;
  assign _028_[1] = _025_[0];
  assign _030_[2:1] = { _024_, _026_[0] };
  assign _032_[2:1] = { _025_[0], _028_[0] };
  assign _037_[0] = _026_[0];
  assign _038_[1:0] = { _026_[0], _030_[0] };
  assign _039_[0] = _033_[0];
  assign _042_[0] = _028_[0];
  assign _043_[1:0] = { _028_[0], _032_[0] };
  assign _044_[0] = _011_[0];
  assign _047_[0] = _030_[0];
  assign _050_[0] = _032_[0];
  assign _055_[0] = _075_[1];
  assign _058_[4:1] = { _055_[4:2], _070_[3] };
  assign _059_[1] = _056_[1];
  assign _061_[2:1] = { _055_[2], _070_[3] };
  assign _064_[4:2] = { _061_[4:3], _055_[2] };
  assign _065_[1] = _062_[1];
  assign _070_[2:0] = { _069_[2], 2'h3 };
  assign _071_[2:0] = { cnt[2], _069_[1:0] };
  assign _075_[0] = _069_[0];
  assign _076_[0] = cnt[0];
  assign _080_[0] = _069_[0];
  assign _081_[0] = cnt[0];
  assign _087_[1:0] = { _069_[1], 1'h1 };
  assign _088_[1:0] = { cnt[1], _069_[0] };
  assign summand[8:5] = { summand[9], summand[9], summand[9], summand[9] };
endmodule
