/* Generated by Yosys 0.45 (git sha1 9ed031ddd, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

module decrement(cnt, n1);
  (* src = "counter.v:10.5-30.8" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8" *)
  wire [9:0] _00_;
  (* src = "counter.v:10.5-30.8" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8" *)
  wire [9:0] _01_;
  wire [4:0] _02_;
  wire [1:0] _03_;
  wire _04_;
  wire [4:0] _05_;
  wire [1:0] _06_;
  wire _07_;
  wire [4:0] _08_;
  wire [1:0] _09_;
  wire _10_;
  (* src = "counter.v:22.17-22.31" *)
  wire _11_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.21-279.23" *)
  wire [9:0] _12_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "4 5 6" *)
  wire [9:0] _13_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "3 4 5 6 7 8" *)
  wire [9:0] _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 4 5 6" *)
  wire [9:0] _18_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "1 2 3 4 5 6 7 8" *)
  wire [9:0] _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _23_;
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _24_;
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _25_;
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _26_;
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _27_;
  (* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _28_;
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _29_;
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _30_;
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _31_;
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _32_;
  (* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _33_;
  (* init = 10'h3ce *)
  (* src = "counter.v:6.29-6.32" *)
  input [9:0] cnt;
  wire [9:0] cnt;
  (* src = "counter.v:10.5-30.8" *)
  output [9:0] n1;
  wire [9:0] n1;
  assign _02_[0] = cnt[0] |(* src = "counter.v:22.17-22.31" *)  _12_[1];
  assign _02_[1] = _12_[2] |(* src = "counter.v:22.17-22.31" *)  _12_[3];
  assign _02_[2] = _12_[4] |(* src = "counter.v:22.17-22.31" *)  _12_[5];
  assign _02_[3] = _12_[6] |(* src = "counter.v:22.17-22.31" *)  _12_[7];
  assign _02_[4] = _12_[8] |(* src = "counter.v:22.17-22.31" *)  _12_[9];
  assign _03_[0] = _02_[0] |(* src = "counter.v:22.17-22.31" *)  _02_[1];
  assign _03_[1] = _02_[2] |(* src = "counter.v:22.17-22.31" *)  _02_[3];
  assign _04_ = _03_[0] |(* src = "counter.v:22.17-22.31" *)  _03_[1];
  assign _11_ = _04_ |(* src = "counter.v:22.17-22.31" *)  _02_[4];
  assign _01_[9] = _22_ |(* src = {0{1'b0}} *)  _20_;
  assign _05_[0] = cnt[0] &(* src = "counter.v:23.21-23.37" *)  cnt[1];
  assign _06_[0] = _05_[0] &(* src = "counter.v:23.21-23.37" *)  _13_[3];
  assign _07_ = _06_[0] &(* src = "counter.v:23.21-23.37" *)  _06_[1];
  assign _15_ = _07_ &(* src = "counter.v:23.21-23.37" *)  _05_[4];
  assign _00_[9] = _17_ |(* src = {0{1'b0}} *)  _15_;
  assign _09_[0] = _18_[1] &(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37" *)  _08_[1];
  assign _10_ = _09_[0] &(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37" *)  _06_[1];
  assign _20_ = _10_ &(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37" *)  _05_[4];
  assign n1[4] = _11_ &(* src = "counter.v:22.17-22.31|counter.v:22.13-28.16" *)  _00_[9];
  assign n1[9] = _11_ ? (* src = "counter.v:22.17-22.31|counter.v:22.13-28.16" *) _00_[9] : _01_[9];
  assign n1[3] = _11_ ? (* src = "counter.v:22.17-22.31|counter.v:22.13-28.16" *) 1'h0 : _01_[9];
  assign _12_[0] = ~(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[0];
  assign _12_[2] = ~(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[2];
  assign _12_[3] = ~(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[3];
  assign _12_[4] = ~(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[4];
  assign _12_[6] = ~(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[6];
  assign _12_[7] = ~(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[7];
  assign _12_[9] = ~(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[9];
  assign _12_[1] = ~(* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[1];
  assign _12_[5] = ~(* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[5];
  assign _12_[8] = ~(* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[8];
  assign _21_ = _18_[9] ^(* src = {0{1'b0}} *)  _18_[8];
  assign _22_ = _21_ ^(* src = {0{1'b0}} *)  _19_[9];
  assign _17_ = _16_ ^(* src = {0{1'b0}} *)  _14_[9];
  assign _16_ = _13_[9] ^(* src = {0{1'b0}} *)  _13_[8];
  assign _19_[9] = cnt[9] ^(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)  _18_[8];
  assign _14_[9] = cnt[9] ^(* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)  _13_[8];
  assign _18_[1] = _12_[1] &(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)  _12_[0];
  assign _29_ = cnt[3] &(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)  _12_[2];
  assign _23_ = cnt[9] &(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)  _12_[8];
  assign _24_ = _05_[3] &(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)  _12_[5];
  assign _30_ = _06_[1] &(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)  _18_[3];
  assign _08_[1] = cnt[3] &(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)  cnt[2];
  assign _05_[4] = cnt[9] &(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)  cnt[8];
  assign _31_ = _05_[4] &(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)  _18_[7];
  assign _32_ = cnt[8] &(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)  _18_[7];
  assign _33_ = _12_[3] |(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)  _29_;
  assign _28_ = _12_[9] |(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)  _23_;
  assign _18_[3] = _33_ |(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)  _09_[0];
  assign _18_[7] = _24_ |(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)  _30_;
  assign _18_[9] = _28_ |(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.12-248.41" *)  _31_;
  assign _18_[8] = _12_[8] |(* src = "counter.v:26.26-26.42|counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.12-248.41" *)  _32_;
  assign _25_ = _06_[1] &(* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)  _13_[3];
  assign _13_[3] = _12_[3] &(* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)  _12_[2];
  assign _05_[2] = cnt[5] &(* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)  _12_[4];
  assign _05_[3] = _12_[7] &(* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)  _12_[6];
  assign _06_[1] = _05_[3] &(* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)  _05_[2];
  assign _26_ = _05_[4] &(* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)  _13_[7];
  assign _27_ = cnt[8] &(* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)  _13_[7];
  assign _13_[7] = _24_ |(* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)  _25_;
  assign _13_[9] = _28_ |(* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.12-248.41" *)  _26_;
  assign _13_[8] = _12_[8] |(* src = "counter.v:23.21-23.37|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.12-248.41" *)  _27_;
  assign _05_[1] = _13_[3];
  assign { _08_[4:2], _08_[0] } = { _05_[4:2], _18_[1] };
  assign _09_[1] = _06_[1];
  assign _13_[2:0] = { _12_[2], 2'h3 };
  assign _14_[2:0] = { cnt[2], _12_[1:0] };
  assign _18_[0] = _12_[0];
  assign _19_[0] = cnt[0];
  assign { n1[8:5], n1[2:0] } = 7'hxx;
endmodule
