/* Generated by Yosys 0.45 (git sha1 9ed031ddd, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

module increment(cnt, n1);
  (* src = "counter.v:10.5-30.8" *)
  (* unused_bits = "0 1 3 4 5 6 7 8 9" *)
  wire [9:0] _00_;
  (* src = "counter.v:10.5-30.8" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9" *)
  wire [9:0] _01_;
  wire [4:0] _02_;
  wire [1:0] _03_;
  wire _04_;
  wire [4:0] _05_;
  wire [1:0] _06_;
  wire _07_;
  wire [4:0] _08_;
  wire [1:0] _09_;
  wire _10_;
  (* src = "counter.v:13.17-13.32" *)
  wire _11_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.21-279.23" *)
  wire [9:0] _12_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 4 5 6" *)
  wire [9:0] _13_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "1 2 3 4 5 6 7 8" *)
  wire [9:0] _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 4 5 6" *)
  wire [9:0] _20_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "2 3 4 5 6 7 8" *)
  wire [9:0] _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _27_;
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _28_;
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _29_;
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _30_;
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _31_;
  (* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _32_;
  (* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _33_;
  (* init = 10'h3ce *)
  (* src = "counter.v:6.29-6.32" *)
  input [9:0] cnt;
  wire [9:0] cnt;
  (* src = "counter.v:10.5-30.8" *)
  output [9:0] n1;
  wire [9:0] n1;
  assign _12_[0] = ~cnt[0];
  assign _02_[0] = cnt[0] |(* src = "counter.v:13.17-13.32" *)  cnt[1];
  assign _02_[1] = cnt[2] |(* src = "counter.v:13.17-13.32" *)  cnt[3];
  assign _02_[2] = _12_[4] |(* src = "counter.v:13.17-13.32" *)  _12_[5];
  assign _02_[3] = _12_[6] |(* src = "counter.v:13.17-13.32" *)  _12_[7];
  assign _02_[4] = _12_[8] |(* src = "counter.v:13.17-13.32" *)  _12_[9];
  assign _03_[0] = _02_[0] |(* src = "counter.v:13.17-13.32" *)  _02_[1];
  assign _03_[1] = _02_[2] |(* src = "counter.v:13.17-13.32" *)  _02_[3];
  assign _04_ = _03_[0] |(* src = "counter.v:13.17-13.32" *)  _03_[1];
  assign _11_ = _04_ |(* src = "counter.v:13.17-13.32" *)  _02_[4];
  assign _06_[0] = _05_[0] &(* src = "counter.v:14.21-14.36" *)  _05_[1];
  assign _07_ = _06_[0] &(* src = "counter.v:14.21-14.36" *)  _06_[1];
  assign _16_ = _07_ &(* src = "counter.v:14.21-14.36" *)  _05_[4];
  assign _00_[2] = _15_ |(* src = {0{1'b0}} *)  _16_;
  assign _08_[0] = cnt[0] &(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36" *)  _12_[1];
  assign _05_[4] = _12_[8] &(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36" *)  _12_[9];
  assign _09_[0] = _08_[0] &(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36" *)  _08_[1];
  assign _06_[1] = _05_[2] &(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36" *)  _05_[3];
  assign _10_ = _09_[0] &(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36" *)  _06_[1];
  assign _23_ = _10_ &(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36" *)  _05_[4];
  assign _01_[3] = _22_ |(* src = {0{1'b0}} *)  _23_;
  assign n1[2] = _11_ &(* src = "counter.v:13.17-13.32|counter.v:13.13-19.16" *)  _00_[2];
  assign n1[3] = _11_ ? (* src = "counter.v:13.17-13.32|counter.v:13.13-19.16" *) 1'h0 : _01_[3];
  assign _15_ = ~(* src = "counter.v:14.21-14.36" *) _17_;
  assign _22_ = ~(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36" *) _24_;
  assign _12_[1] = ~(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[1];
  assign _12_[2] = ~(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[2];
  assign _12_[3] = ~(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[3];
  assign _12_[7] = ~(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[7];
  assign _12_[4] = ~(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[4];
  assign _12_[5] = ~(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[5];
  assign _12_[6] = ~(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[6];
  assign _12_[8] = ~(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[8];
  assign _12_[9] = ~(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:279.31-279.37" *) cnt[9];
  assign _17_ = _19_ |(* src = {0{1'b0}} *)  _16_;
  assign _19_ = _18_ ^(* src = {0{1'b0}} *)  _14_[9];
  assign _18_ = _13_[9] ^(* src = {0{1'b0}} *)  _13_[8];
  assign _24_ = _26_ |(* src = {0{1'b0}} *)  _23_;
  assign _26_ = _25_ ^(* src = {0{1'b0}} *)  _21_[9];
  assign _25_ = _20_[9] ^(* src = {0{1'b0}} *)  _20_[8];
  assign _14_[9] = _12_[9] ^(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)  _13_[8];
  assign _21_[9] = _12_[9] ^(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:289.13-289.25" *)  _20_[8];
  assign _05_[0] = cnt[1] &(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)  _12_[0];
  assign _08_[1] = _12_[3] &(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)  _12_[2];
  assign _27_ = cnt[7] &(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)  _12_[6];
  assign _28_ = _05_[1] &(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)  _13_[1];
  assign _29_ = _05_[3] &(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)  _12_[5];
  assign _30_ = _06_[1] &(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)  _13_[3];
  assign _05_[1] = _12_[3] &(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)  cnt[2];
  assign _05_[3] = cnt[7] &(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)  cnt[6];
  assign _13_[9] = _05_[4] &(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)  _13_[7];
  assign _13_[8] = _12_[8] &(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)  _13_[7];
  assign _13_[1] = _12_[1] |(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)  _05_[0];
  assign _31_ = _12_[7] |(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)  _27_;
  assign _13_[3] = _08_[1] |(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)  _28_;
  assign _13_[7] = _32_ |(* src = "counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)  _30_;
  assign _20_[3] = _08_[1] &(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)  _12_[1];
  assign _33_ = _06_[1] &(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.19-240.41" *)  _20_[3];
  assign _05_[2] = cnt[5] &(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:241.12-241.34" *)  _12_[4];
  assign _20_[9] = _05_[4] &(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)  _20_[7];
  assign _20_[8] = _12_[8] &(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:248.19-248.41" *)  _20_[7];
  assign _32_ = _31_ |(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)  _29_;
  assign _20_[7] = _32_ |(* src = "counter.v:17.26-17.41|counter.v:14.21-14.36|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:286.27-286.69|/home/lukas/tabby-linux-x64-20240903/tabby/lib/../share/yosys/techmap.v:240.12-240.41" *)  _33_;
  assign _08_[4:2] = _05_[4:2];
  assign _09_[1] = _06_[1];
  assign _13_[0] = _12_[0];
  assign _14_[0] = cnt[0];
  assign _20_[1:0] = { _12_[1], 1'h1 };
  assign _21_[1:0] = { cnt[1], _12_[0] };
  assign { n1[9:4], n1[1:0] } = 8'hxx;
endmodule
